In [1]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import os
from tqdm import tqdm

# Suppress TensorFlow warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
tf.get_logger().setLevel('ERROR')

print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.10.0

In [2]:
# GPU Configuration
print("=" * 60)
print("GPU CONFIGURATION")
print("=" * 60)
print(f"TensorFlow version: {tf.__version__}")
print(f"Num GPUs Available: {len(tf.config.list_physical_devices('GPU'))}")

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print(f"✓ GPU detected and configured")
    except RuntimeError as e:
        print(f"GPU configuration error: {e}")
else:
    print("⚠ No GPU detected - Running on CPU")
print("=" * 60 + "\n")

============================================================
GPU CONFIGURATION
============================================================
TensorFlow version: 2.10.0
Num GPUs Available: 1
✓ GPU detected and configured
============================================================

## Configuration

In [3]:
# Federated Learning Configuration
NUM_CLIENTS = 50
NUM_ROUNDS = 100        
FIXED_EPOCHS = 10         # Fixed epochs for all clients each round
BATCH_SIZE = 32           # SAME as original (32 not 64)

# Dataset details
SAMPLES_PER_CLASS_PER_CLIENT = 60
SAMPLES_PER_CLIENT = 1200  # 60000 total / 50 clients

# Adaptive Training Parameters
NUM_BOTTOM_CLIENTS = 10   # Number of lowest performers to get adaptive training
MAX_ADAPTIVE_EPOCHS = 50  # Maximum total epochs (including fixed 10)
ADAPTIVE_EPOCHS_STEP = 5 # Train in steps of 5 epochs during adaptive phase

# Directories
CLIENT_DATA_DIR = 'dataset_60perclass/clients_50_from_100x60'
TEST_DATA_DIR = 'dataset_60perclass'  # Keep same 10k disjoint test set as before
RESULTS_DIR = 'results_adaptive_weight_rejection_60_per_class_50_clients'
os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(f'{RESULTS_DIR}/plots', exist_ok=True)

## Load Data

In [4]:
# Load test data (common for all clients)
print("Loading common test dataset...")
test_file = os.path.join(TEST_DATA_DIR, 'test_10000_samples_disjoint.npz')
test_data = np.load(test_file)

x_test = test_data['x'] / 255.0
y_test = test_data['y']
x_test = x_test.reshape(len(x_test), 28*28)

if len(x_test) != 10000:
    raise ValueError(f"Expected 10000 test samples, found {len(x_test)}")

print(f"✓ Test data loaded from {test_file}: {x_test.shape}")
print(f"  Labels shape: {y_test.shape}")

Loading common test dataset...
✓ Test data loaded from dataset_60perclass\test_10000_samples_disjoint.npz: (10000, 784)
  Labels shape: (10000,)

In [5]:
# Load all client data
print(f"\nLoading data for {NUM_CLIENTS} clients...")
client_data = []

for client_id in range(1, NUM_CLIENTS + 1):
    client_file = os.path.join(CLIENT_DATA_DIR, f'client_{client_id}.npz')
    data = np.load(client_file)
    
    x_client = data['x'] / 255.0
    y_client = data['y']
    x_client = x_client.reshape(len(x_client), 28*28)
    
    client_data.append({
        'x_train': x_client,
        'y_train': y_client,
        'x_test': x_test,
        'y_test': y_test
    })
    
    if client_id % 20 == 0:
        print(f"  Loaded {client_id}/{NUM_CLIENTS} clients")

print(f"\n✓ All {NUM_CLIENTS} clients loaded successfully")
print(f"  Each client: {len(client_data[0]['x_train'])} training samples")
print(f"  Common test set: {len(x_test)} samples\n")

Loading data for 50 clients...
  Loaded 20/50 clients
  Loaded 40/50 clients

✓ All 50 clients loaded successfully
  Each client: 1200 training samples
  Common test set: 10000 samples

## Model Architecture

In [6]:
# Define model - SAME as original weight rejection (simpler, proven to work)
def create_model():
    """Lightweight model optimized for small datasets"""
    model = keras.Sequential([
        keras.layers.Dense(64, input_shape=(784,), activation="relu"),
        keras.layers.Dropout(0.3),
        keras.layers.Dense(32, activation="relu"),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(10, activation="softmax")
    ])
    
    # Compile with SAME hyperparameters as original
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.001),  # Higher LR than before
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

# Test model
print("Testing model architecture...")
test_model = create_model()
test_model.summary()
print("\n✓ Model architecture validated (same as working version)\n")

Testing model architecture...
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                50240

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 32)                2080

 dropout_1 (Dropout)         (None, 32)                0

 dense_2 (Dense)             (None, 10)                330

=================================================================
Total params: 52,650
Trainable params: 52,650
Non-trainable params: 0
_________________________________________________________________

✓ Model architecture validated (same as working version)

## Helper Functions

In [ ]:
# Average aggregation function
def fed_avg(weights_list):
    """Aggregate weights from all clients using coordinate-wise average."""
    avg_weights = []
    for weights_tuple in zip(*weights_list):
        avg_weights.append(np.mean(weights_tuple, axis=0))
    return avg_weights

print("✓ Average aggregation function defined")

✓ Median aggregation function defined

## Initialize Training

In [8]:
# Initialize global model and tracking
print("=" * 60)
print("INITIALIZING FEDERATED LEARNING")
print("=" * 60)

global_model = create_model()
global_weights = global_model.get_weights()

# Tracking arrays
client_test_acc_history = [[] for _ in range(NUM_CLIENTS)]
client_train_acc_history = [[] for _ in range(NUM_CLIENTS)]
client_best_weights = [None for _ in range(NUM_CLIENTS)]
client_best_test_acc = [0.0 for _ in range(NUM_CLIENTS)]
client_best_train_acc = [0.0 for _ in range(NUM_CLIENTS)]
client_rejections = [[] for _ in range(NUM_CLIENTS)]
client_epochs_used = [[] for _ in range(NUM_CLIENTS)]
client_adaptive_rounds = [[] for _ in range(NUM_CLIENTS)]

print("✓ Global model initialized")
print("✓ Tracking arrays created")
print("✓ Weight rejection + adaptive epochs ready\n")

============================================================
INITIALIZING FEDERATED LEARNING
============================================================
✓ Global model initialized
✓ Tracking arrays created
✓ Weight rejection + adaptive epochs ready

## Main Training Loop

In [9]:
# Main federated training loop
print("=" * 70)
print("STARTING FEDERATED TRAINING")
print("=" * 70 + "\n")

for round_num in tqdm(range(NUM_ROUNDS), desc="Communication Rounds", unit="round"):
    print(f"\n{'='*70}")
    print(f"ROUND {round_num + 1}/{NUM_ROUNDS}")
    print(f"{'='*70}")
    
    local_weights = []
    round_test_accs = []
    round_train_accs = []
    round_rejections = 0
    round_acceptances = 0
    round_client_results = []  # Store (client_id, test_acc, epochs_used) for sorting
    
    # ═══════════════════════════════════════════════════════════
    # PHASE 1: Fixed Training for ALL Clients
    # ═══════════════════════════════════════════════════════════
    print(f"\nPhase 1: Training all {NUM_CLIENTS} clients for {FIXED_EPOCHS} epochs...")
    
    client_round_data = {}  # Store results before weight rejection decision
    
    for client_id in tqdm(range(NUM_CLIENTS), desc="Fixed Training", unit="client", leave=False):
        # Create fresh model
        client_model = create_model()
        client_model.set_weights(global_weights)
        
        # Get client's data
        x_train = client_data[client_id]['x_train']
        y_train = client_data[client_id]['y_train']
        x_test = client_data[client_id]['x_test']
        y_test = client_data[client_id]['y_test']
        
        # Store old accuracy for comparison
        old_test_acc = client_best_test_acc[client_id]
        old_train_acc = client_best_train_acc[client_id]
        
        # Train for fixed epochs (SIMPLE, FAST)
        history = client_model.fit(
            x_train, y_train,
            epochs=FIXED_EPOCHS,
            batch_size=BATCH_SIZE,
            verbose=0
        )
        fixed_train_acc = float(history.history['accuracy'][-1])
        
        # Evaluate on test data
        _, new_test_acc = client_model.evaluate(x_test, y_test, verbose=0)
        new_weights = [w.copy() for w in client_model.get_weights()]
        
        # Store results temporarily
        client_round_data[client_id] = {
            'old_acc': old_test_acc,
            'old_train_acc': old_train_acc,
            'new_acc': new_test_acc,
            'new_train_acc': fixed_train_acc,
            'new_weights': new_weights,
            'epochs_used': FIXED_EPOCHS,
            'got_adaptive': False
        }
        
        # Store for sorting (to find bottom performers)
        round_client_results.append((client_id, new_test_acc, FIXED_EPOCHS))
        
        # Clear GPU memory after each client training
        del client_model
        tf.keras.backend.clear_session()
    
    # ═══════════════════════════════════════════════════════════
    # PHASE 2: Adaptive Training for Bottom Performers
    # ═══════════════════════════════════════════════════════════
    print(f"\nPhase 2: Adaptive training for bottom {NUM_BOTTOM_CLIENTS} clients...")
    
    # Sort by test accuracy (ascending - lowest first)
    round_client_results.sort(key=lambda x: x[1])
    bottom_clients = [cid for cid, _, _ in round_client_results[:NUM_BOTTOM_CLIENTS]]
    
    print(f"Bottom {NUM_BOTTOM_CLIENTS} clients identified:")
    for i, (cid, acc, _) in enumerate(round_client_results[:NUM_BOTTOM_CLIENTS]):
        print(f"  {i+1}. Client {cid+1}: {acc*100:.2f}%")
    
    adaptive_improved = 0
    for client_id in tqdm(bottom_clients, desc="Adaptive Training", unit="client", leave=False):
        data = client_round_data[client_id]
        target_acc = data['old_acc']
        current_acc = data['new_acc']
        
        # Only do adaptive training if they haven't improved yet
        if current_acc <= target_acc and target_acc > 0:
            # Create model with current weights
            client_model = create_model()
            client_model.set_weights(data['new_weights'])
            
            x_train = client_data[client_id]['x_train']
            y_train = client_data[client_id]['y_train']
            x_test = client_data[client_id]['x_test']
            y_test = client_data[client_id]['y_test']
            
            best_adaptive_acc = current_acc
            best_adaptive_train_acc = data['new_train_acc']
            best_adaptive_weights = data['new_weights']
            total_epochs = FIXED_EPOCHS
            
            # Train in steps until improvement or max epochs
            while total_epochs < MAX_ADAPTIVE_EPOCHS:
                client_model.fit(
                    x_train, y_train,
                    epochs=ADAPTIVE_EPOCHS_STEP,
                    batch_size=BATCH_SIZE,
                    verbose=0
                )
                
                total_epochs += ADAPTIVE_EPOCHS_STEP
                _, test_acc = client_model.evaluate(x_test, y_test, verbose=0)
                _, train_acc = client_model.evaluate(x_train, y_train, verbose=0)
                
                # Track best
                if test_acc > best_adaptive_acc:
                    best_adaptive_acc = test_acc
                    best_adaptive_train_acc = train_acc
                    best_adaptive_weights = [w.copy() for w in client_model.get_weights()]
                
                # Stop if improved beyond target
                if test_acc > target_acc:
                    adaptive_improved += 1
                    break
            
            # Update client data with best adaptive results
            client_round_data[client_id]['new_acc'] = best_adaptive_acc
            client_round_data[client_id]['new_train_acc'] = best_adaptive_train_acc
            client_round_data[client_id]['new_weights'] = best_adaptive_weights
            client_round_data[client_id]['epochs_used'] = total_epochs
            client_round_data[client_id]['got_adaptive'] = True
            
            # Clear GPU memory after adaptive training
            del client_model
            tf.keras.backend.clear_session()
    
    if adaptive_improved > 0:
        print(f"  ✓ {adaptive_improved}/{len(bottom_clients)} clients improved with adaptive training")
    
    # ═══════════════════════════════════════════════════════════
    # PHASE 3: Weight Rejection Decision
    # ═══════════════════════════════════════════════════════════
    print(f"\nPhase 3: Weight rejection decision...")
    
    for client_id in range(NUM_CLIENTS):
        data = client_round_data[client_id]
        old_acc = data['old_acc']
        new_acc = data['new_acc']
        old_train_acc = data['old_train_acc']
        new_train_acc = data['new_train_acc']
        epochs_used = data['epochs_used']
        
        # DECISION: Accept only if improved
        if new_acc > old_acc:
            # ACCEPT
            client_best_weights[client_id] = data['new_weights']
            client_best_test_acc[client_id] = new_acc
            client_best_train_acc[client_id] = new_train_acc
            client_rejections[client_id].append(0)
            round_acceptances += 1
            final_test_acc = new_acc
            final_train_acc = new_train_acc
        else:
            # REJECT - keep old weights
            if client_best_weights[client_id] is None:
                # First round - accept anyway
                client_best_weights[client_id] = data['new_weights']
                client_best_test_acc[client_id] = new_acc
                client_best_train_acc[client_id] = new_train_acc
                client_rejections[client_id].append(0)
                round_acceptances += 1
                final_test_acc = new_acc
                final_train_acc = new_train_acc
            else:
                # Reject, use previous best
                client_rejections[client_id].append(1)
                round_rejections += 1
                final_test_acc = client_best_test_acc[client_id]
                final_train_acc = client_best_train_acc[client_id]
        
        # Track results
        client_test_acc_history[client_id].append(final_test_acc)
        client_train_acc_history[client_id].append(final_train_acc)
        client_epochs_used[client_id].append(epochs_used)
        client_adaptive_rounds[client_id].append(1 if data['got_adaptive'] else 0)
        round_test_accs.append(final_test_acc)
        round_train_accs.append(final_train_acc)
        
        # Collect best weights for FedAvg aggregation
        local_weights.append(client_best_weights[client_id])
    
    # ═══════════════════════════════════════════════════════════
    # FedAvg
    # ═══════════════════════════════════════════════════════════
    global_weights = fed_avg(local_weights)
    global_model.set_weights(global_weights)
    
    # Round summary
    median_test_acc = np.median(round_test_accs) * 100
    median_train_acc = np.median(round_train_accs) * 100
    min_test_acc = np.min(round_test_accs) * 100
    max_test_acc = np.max(round_test_accs) * 100
    std_test_acc = np.std([acc * 100 for acc in round_test_accs])
    total_adaptive = sum([1 for cid in range(NUM_CLIENTS) if client_round_data[cid]['got_adaptive']])
    
    print(f"\n📊 Round {round_num + 1} Summary:")
    print(f"   Median Test Accuracy: {median_test_acc:.2f}%")
    print(f"   Median Train Accuracy: {median_train_acc:.2f}%")
    print(f"   Std Dev: {std_test_acc:.2f}%")
    print(f"   Range: [{min_test_acc:.2f}%, {max_test_acc:.2f}%]")
    print(f"   Weights Accepted: {round_acceptances}/{NUM_CLIENTS}")
    print(f"   Weights Rejected: {round_rejections}/{NUM_CLIENTS}")
    print(f"   Adaptive Training: {total_adaptive}/{NUM_CLIENTS} clients")

print("\n" + "="*70)
print("FEDERATED TRAINING COMPLETE!")
print("="*70 + "\n")

======================================================================
STARTING FEDERATED TRAINING
======================================================================

Communication Rounds:   0%|          | 0/100 [00:00<?, ?round/s]

======================================================================
ROUND 1/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 9: 88.77%
  2. Client 36: 88.77%
  3. Client 2: 88.85%
  4. Client 49: 88.90%
  5. Client 46: 88.93%
  6. Client 13: 88.94%
  7. Client 43: 88.98%
  8. Client 19: 89.09%
  9. Client 45: 89.09%
  10. Client 22: 89.13%

Communication Rounds:   1%|          | 1/100 [05:02<8:19:06, 302.49s/round]

Phase 3: Weight rejection decision...

📊 Round 1 Summary:
   Median Test Accuracy: 89.54%
   Median Train Accuracy: 86.96%
   Std Dev: 0.45%
   Range: [88.77%, 90.53%]
   Weights Accepted: 50/50
   Weights Rejected: 0/50
   Adaptive Training: 0/50 clients

======================================================================
ROUND 2/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 43: 90.26%
  2. Client 2: 90.55%
  3. Client 49: 90.58%
  4. Client 15: 90.70%
  5. Client 26: 90.70%
  6. Client 35: 90.88%
  7. Client 46: 90.93%
  8. Client 19: 90.98%
  9. Client 16: 91.02%
  10. Client 20: 91.07%

Communication Rounds:   2%|▏         | 2/100 [09:49<7:59:16, 293.44s/round]

Phase 3: Weight rejection decision...

📊 Round 2 Summary:
   Median Test Accuracy: 91.36%
   Median Train Accuracy: 92.13%
   Std Dev: 0.37%
   Range: [90.26%, 92.14%]
   Weights Accepted: 50/50
   Weights Rejected: 0/50
   Adaptive Training: 0/50 clients

======================================================================
ROUND 3/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 20: 91.32%
  2. Client 46: 92.06%
  3. Client 10: 92.12%
  4. Client 35: 92.12%
  5. Client 8: 92.13%
  6. Client 25: 92.24%
  7. Client 38: 92.24%
  8. Client 2: 92.32%
  9. Client 36: 92.32%
  10. Client 3: 92.34%

Communication Rounds:   3%|▎         | 3/100 [14:25<7:41:13, 285.29s/round]

Phase 3: Weight rejection decision...

📊 Round 3 Summary:
   Median Test Accuracy: 92.56%
   Median Train Accuracy: 94.04%
   Std Dev: 0.30%
   Range: [91.32%, 93.08%]
   Weights Accepted: 50/50
   Weights Rejected: 0/50
   Adaptive Training: 0/50 clients

======================================================================
ROUND 4/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 35: 92.66%
  2. Client 16: 92.70%
  3. Client 38: 92.70%
  4. Client 8: 92.76%
  5. Client 46: 92.82%
  6. Client 29: 92.85%
  7. Client 43: 92.85%
  8. Client 9: 92.90%
  9. Client 40: 92.96%
  10. Client 50: 92.98%

Communication Rounds:   4%|▍         | 4/100 [18:06<6:56:20, 260.22s/round]

Phase 3: Weight rejection decision...

📊 Round 4 Summary:
   Median Test Accuracy: 93.20%
   Median Train Accuracy: 95.29%
   Std Dev: 0.28%
   Range: [92.66%, 93.80%]
   Weights Accepted: 50/50
   Weights Rejected: 0/50
   Adaptive Training: 0/50 clients

======================================================================
ROUND 5/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 38: 93.18%
  2. Client 49: 93.20%
  3. Client 3: 93.28%
  4. Client 41: 93.28%
  5. Client 40: 93.30%
  6. Client 35: 93.35%
  7. Client 7: 93.38%
  8. Client 16: 93.39%
  9. Client 2: 93.40%
  10. Client 23: 93.43%

Communication Rounds:   5%|▌         | 5/100 [19:12<5:00:37, 189.87s/round]

Phase 3: Weight rejection decision...

📊 Round 5 Summary:
   Median Test Accuracy: 93.73%
   Median Train Accuracy: 95.67%
   Std Dev: 0.26%
   Range: [93.18%, 94.20%]
   Weights Accepted: 50/50
   Weights Rejected: 0/50
   Adaptive Training: 0/50 clients

======================================================================
ROUND 6/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 9: 93.34%
  2. Client 29: 93.58%
  3. Client 16: 93.61%
  4. Client 38: 93.68%
  5. Client 43: 93.69%
  6. Client 35: 93.73%
  7. Client 13: 93.74%
  8. Client 18: 93.81%
  9. Client 41: 93.81%
  10. Client 7: 93.82%

Communication Rounds:   6%|▌         | 6/100 [20:19<3:52:20, 148.31s/round]

  ✓ 2/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 6 Summary:
   Median Test Accuracy: 94.10%
   Median Train Accuracy: 96.17%
   Std Dev: 0.22%
   Range: [93.61%, 94.48%]
   Weights Accepted: 49/50
   Weights Rejected: 1/50
   Adaptive Training: 2/50 clients

======================================================================
ROUND 7/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 26: 93.63%
  2. Client 16: 93.66%
  3. Client 33: 93.81%
  4. Client 8: 93.91%
  5. Client 29: 93.92%
  6. Client 49: 93.94%
  7. Client 18: 93.96%
  8. Client 4: 94.08%
  9. Client 41: 94.09%
  10. Client 35: 94.12%

Communication Rounds:   7%|▋         | 7/100 [21:52<3:21:29, 130.00s/round]

  ✓ 2/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 7 Summary:
   Median Test Accuracy: 94.35%
   Median Train Accuracy: 96.54%
   Std Dev: 0.22%
   Range: [93.66%, 94.81%]
   Weights Accepted: 42/50
   Weights Rejected: 8/50
   Adaptive Training: 5/50 clients

======================================================================
ROUND 8/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 9: 93.94%
  2. Client 38: 93.99%
  3. Client 16: 94.02%
  4. Client 8: 94.09%
  5. Client 7: 94.10%
  6. Client 18: 94.12%
  7. Client 35: 94.13%
  8. Client 15: 94.18%
  9. Client 3: 94.22%
  10. Client 20: 94.25%

Communication Rounds:   8%|▊         | 8/100 [23:41<3:09:19, 123.47s/round]

  ✓ 1/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 8 Summary:
   Median Test Accuracy: 94.56%
   Median Train Accuracy: 96.67%
   Std Dev: 0.22%
   Range: [94.02%, 94.97%]
   Weights Accepted: 37/50
   Weights Rejected: 13/50
   Adaptive Training: 7/50 clients

======================================================================
ROUND 9/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 9: 94.00%
  2. Client 23: 94.10%
  3. Client 7: 94.24%
  4. Client 29: 94.31%
  5. Client 41: 94.31%
  6. Client 2: 94.35%
  7. Client 15: 94.39%
  8. Client 38: 94.40%
  9. Client 8: 94.42%
  10. Client 35: 94.42%

Communication Rounds:   9%|▉         | 9/100 [25:06<2:49:08, 111.52s/round]

  ✓ 3/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 9 Summary:
   Median Test Accuracy: 94.68%
   Median Train Accuracy: 96.83%
   Std Dev: 0.19%
   Range: [94.29%, 95.01%]
   Weights Accepted: 35/50
   Weights Rejected: 15/50
   Adaptive Training: 5/50 clients

======================================================================
ROUND 10/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 8: 94.12%
  2. Client 45: 94.28%
  3. Client 46: 94.33%
  4. Client 16: 94.34%
  5. Client 7: 94.40%
  6. Client 23: 94.51%
  7. Client 41: 94.51%
  8. Client 26: 94.53%
  9. Client 50: 94.55%
  10. Client 3: 94.56%

Communication Rounds:  10%|█         | 10/100 [27:00<2:48:05, 112.06s/round]

Phase 3: Weight rejection decision...

📊 Round 10 Summary:
   Median Test Accuracy: 94.82%
   Median Train Accuracy: 97.00%
   Std Dev: 0.19%
   Range: [94.40%, 95.22%]
   Weights Accepted: 31/50
   Weights Rejected: 19/50
   Adaptive Training: 7/50 clients

======================================================================
ROUND 11/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 43: 94.13%
  2. Client 35: 94.26%
  3. Client 19: 94.40%
  4. Client 44: 94.43%
  5. Client 7: 94.44%
  6. Client 20: 94.47%
  7. Client 5: 94.49%
  8. Client 16: 94.50%
  9. Client 41: 94.53%
  10. Client 9: 94.54%

Communication Rounds:  11%|█         | 11/100 [28:54<2:47:07, 112.67s/round]

  ✓ 1/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 11 Summary:
   Median Test Accuracy: 94.92%
   Median Train Accuracy: 97.17%
   Std Dev: 0.19%
   Range: [94.44%, 95.39%]
   Weights Accepted: 35/50
   Weights Rejected: 15/50
   Adaptive Training: 8/50 clients

======================================================================
ROUND 12/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 16: 93.85%
  2. Client 35: 94.38%
  3. Client 46: 94.59%
  4. Client 41: 94.65%
  5. Client 44: 94.66%
  6. Client 8: 94.68%
  7. Client 3: 94.72%
  8. Client 4: 94.73%
  9. Client 7: 94.75%
  10. Client 43: 94.76%

Communication Rounds:  12%|█▏        | 12/100 [30:48<2:45:54, 113.12s/round]

Phase 3: Weight rejection decision...

📊 Round 12 Summary:
   Median Test Accuracy: 95.02%
   Median Train Accuracy: 97.17%
   Std Dev: 0.18%
   Range: [94.56%, 95.39%]
   Weights Accepted: 29/50
   Weights Rejected: 21/50
   Adaptive Training: 7/50 clients

======================================================================
ROUND 13/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 9: 94.37%
  2. Client 4: 94.48%
  3. Client 7: 94.56%
  4. Client 41: 94.59%
  5. Client 16: 94.62%
  6. Client 8: 94.65%
  7. Client 36: 94.75%
  8. Client 43: 94.78%
  9. Client 39: 94.80%
  10. Client 18: 94.82%

Communication Rounds:  13%|█▎        | 13/100 [32:31<2:39:42, 110.15s/round]

  ✓ 3/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 13 Summary:
   Median Test Accuracy: 95.10%
   Median Train Accuracy: 97.25%
   Std Dev: 0.21%
   Range: [94.62%, 95.58%]
   Weights Accepted: 27/50
   Weights Rejected: 23/50
   Adaptive Training: 8/50 clients

======================================================================
ROUND 14/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 5: 94.50%
  2. Client 49: 94.63%
  3. Client 16: 94.68%
  4. Client 38: 94.73%
  5. Client 9: 94.75%
  6. Client 35: 94.75%
  7. Client 41: 94.78%
  8. Client 44: 94.86%
  9. Client 4: 94.89%
  10. Client 29: 94.91%

Communication Rounds:  14%|█▍        | 14/100 [34:30<2:41:34, 112.72s/round]

  ✓ 1/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 14 Summary:
   Median Test Accuracy: 95.14%
   Median Train Accuracy: 97.21%
   Std Dev: 0.20%
   Range: [94.68%, 95.69%]
   Weights Accepted: 26/50
   Weights Rejected: 24/50
   Adaptive Training: 8/50 clients

======================================================================
ROUND 15/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 37: 94.59%
  2. Client 41: 94.61%
  3. Client 13: 94.72%
  4. Client 9: 94.73%
  5. Client 35: 94.81%
  6. Client 43: 94.87%
  7. Client 42: 94.89%
  8. Client 8: 94.91%
  9. Client 14: 94.93%
  10. Client 40: 94.93%

Communication Rounds:  15%|█▌        | 15/100 [36:43<2:48:25, 118.89s/round]

Phase 3: Weight rejection decision...

📊 Round 15 Summary:
   Median Test Accuracy: 95.21%
   Median Train Accuracy: 97.38%
   Std Dev: 0.20%
   Range: [94.78%, 95.69%]
   Weights Accepted: 20/50
   Weights Rejected: 30/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 16/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 16: 94.65%
  2. Client 35: 94.79%
  3. Client 29: 94.83%
  4. Client 7: 94.90%
  5. Client 44: 94.95%
  6. Client 46: 94.99%
  7. Client 48: 94.99%
  8. Client 8: 95.00%
  9. Client 19: 95.01%
  10. Client 38: 95.01%

Communication Rounds:  16%|█▌        | 16/100 [38:59<2:53:46, 124.13s/round]

Phase 3: Weight rejection decision...

📊 Round 16 Summary:
   Median Test Accuracy: 95.30%
   Median Train Accuracy: 97.42%
   Std Dev: 0.19%
   Range: [94.84%, 95.69%]
   Weights Accepted: 24/50
   Weights Rejected: 26/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 17/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 4: 94.50%
  2. Client 7: 94.75%
  3. Client 23: 94.76%
  4. Client 35: 94.76%
  5. Client 8: 94.77%
  6. Client 50: 94.88%
  7. Client 9: 94.91%
  8. Client 37: 94.99%
  9. Client 2: 95.01%
  10. Client 44: 95.02%

Communication Rounds:  17%|█▋        | 17/100 [41:08<2:53:34, 125.47s/round]

  ✓ 1/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 17 Summary:
   Median Test Accuracy: 95.34%
   Median Train Accuracy: 97.42%
   Std Dev: 0.19%
   Range: [94.84%, 95.72%]
   Weights Accepted: 17/50
   Weights Rejected: 33/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 18/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 50: 94.85%
  2. Client 20: 94.91%
  3. Client 43: 94.97%
  4. Client 7: 94.99%
  5. Client 16: 94.99%
  6. Client 46: 95.00%
  7. Client 19: 95.01%
  8. Client 44: 95.01%
  9. Client 29: 95.04%
  10. Client 4: 95.09%

Communication Rounds:  18%|█▊        | 18/100 [43:09<2:49:43, 124.19s/round]

Phase 3: Weight rejection decision...

📊 Round 18 Summary:
   Median Test Accuracy: 95.36%
   Median Train Accuracy: 97.50%
   Std Dev: 0.17%
   Range: [94.99%, 95.72%]
   Weights Accepted: 17/50
   Weights Rejected: 33/50
   Adaptive Training: 8/50 clients

======================================================================
ROUND 19/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 9: 94.66%
  2. Client 16: 94.69%
  3. Client 35: 94.96%
  4. Client 4: 95.01%
  5. Client 38: 95.03%
  6. Client 21: 95.06%
  7. Client 39: 95.10%
  8. Client 44: 95.16%
  9. Client 41: 95.18%
  10. Client 48: 95.18%

Communication Rounds:  19%|█▉        | 19/100 [45:17<2:49:03, 125.22s/round]

Phase 3: Weight rejection decision...

📊 Round 19 Summary:
   Median Test Accuracy: 95.39%
   Median Train Accuracy: 97.58%
   Std Dev: 0.15%
   Range: [95.08%, 95.72%]
   Weights Accepted: 14/50
   Weights Rejected: 36/50
   Adaptive Training: 9/50 clients

======================================================================
ROUND 20/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 38: 94.58%
  2. Client 44: 94.66%
  3. Client 7: 94.82%
  4. Client 9: 94.82%
  5. Client 26: 94.92%
  6. Client 33: 94.94%
  7. Client 4: 94.95%
  8. Client 45: 95.01%
  9. Client 24: 95.03%
  10. Client 8: 95.06%

Communication Rounds:  20%|██        | 20/100 [47:31<2:50:34, 127.93s/round]

Phase 3: Weight rejection decision...

📊 Round 20 Summary:
   Median Test Accuracy: 95.44%
   Median Train Accuracy: 97.58%
   Std Dev: 0.15%
   Range: [95.09%, 95.76%]
   Weights Accepted: 15/50
   Weights Rejected: 35/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 21/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 41: 94.70%
  2. Client 34: 94.85%
  3. Client 38: 94.86%
  4. Client 16: 94.96%
  5. Client 4: 94.99%
  6. Client 43: 95.03%
  7. Client 49: 95.07%
  8. Client 9: 95.08%
  9. Client 11: 95.11%
  10. Client 37: 95.11%

Communication Rounds:  21%|██        | 21/100 [49:46<2:51:11, 130.02s/round]

Phase 3: Weight rejection decision...

📊 Round 21 Summary:
   Median Test Accuracy: 95.49%
   Median Train Accuracy: 97.46%
   Std Dev: 0.15%
   Range: [95.09%, 95.76%]
   Weights Accepted: 18/50
   Weights Rejected: 32/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 22/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 38: 94.81%
  2. Client 37: 94.99%
  3. Client 49: 95.02%
  4. Client 16: 95.03%
  5. Client 5: 95.10%
  6. Client 8: 95.19%
  7. Client 34: 95.20%
  8. Client 43: 95.20%
  9. Client 9: 95.22%
  10. Client 39: 95.25%

Communication Rounds:  22%|██▏       | 22/100 [51:48<2:45:53, 127.61s/round]

  ✓ 1/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 22 Summary:
   Median Test Accuracy: 95.52%
   Median Train Accuracy: 97.54%
   Std Dev: 0.14%
   Range: [95.18%, 95.76%]
   Weights Accepted: 14/50
   Weights Rejected: 36/50
   Adaptive Training: 9/50 clients

======================================================================
ROUND 23/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 44: 94.81%
  2. Client 16: 94.91%
  3. Client 24: 94.91%
  4. Client 34: 94.92%
  5. Client 41: 94.93%
  6. Client 35: 95.03%
  7. Client 22: 95.12%
  8. Client 43: 95.12%
  9. Client 7: 95.13%
  10. Client 45: 95.13%

Communication Rounds:  23%|██▎       | 23/100 [54:03<2:46:45, 129.94s/round]

Phase 3: Weight rejection decision...

📊 Round 23 Summary:
   Median Test Accuracy: 95.53%
   Median Train Accuracy: 97.54%
   Std Dev: 0.14%
   Range: [95.18%, 95.89%]
   Weights Accepted: 11/50
   Weights Rejected: 39/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 24/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 44: 94.99%
  2. Client 7: 95.00%
  3. Client 35: 95.01%
  4. Client 38: 95.09%
  5. Client 9: 95.10%
  6. Client 36: 95.10%
  7. Client 21: 95.13%
  8. Client 20: 95.16%
  9. Client 30: 95.18%
  10. Client 8: 95.19%

Communication Rounds:  24%|██▍       | 24/100 [56:17<2:46:02, 131.09s/round]

Phase 3: Weight rejection decision...

📊 Round 24 Summary:
   Median Test Accuracy: 95.54%
   Median Train Accuracy: 97.58%
   Std Dev: 0.13%
   Range: [95.22%, 95.89%]
   Weights Accepted: 8/50
   Weights Rejected: 42/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 25/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 40: 94.93%
  2. Client 7: 94.96%
  3. Client 16: 95.02%
  4. Client 15: 95.09%
  5. Client 49: 95.17%
  6. Client 3: 95.18%
  7. Client 20: 95.18%
  8. Client 39: 95.19%
  9. Client 33: 95.20%
  10. Client 35: 95.21%

Communication Rounds:  25%|██▌       | 25/100 [58:32<2:45:27, 132.36s/round]

Phase 3: Weight rejection decision...

📊 Round 25 Summary:
   Median Test Accuracy: 95.56%
   Median Train Accuracy: 97.67%
   Std Dev: 0.14%
   Range: [95.22%, 95.90%]
   Weights Accepted: 9/50
   Weights Rejected: 41/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 26/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 49: 95.02%
  2. Client 39: 95.11%
  3. Client 9: 95.16%
  4. Client 3: 95.18%
  5. Client 16: 95.21%
  6. Client 23: 95.21%
  7. Client 4: 95.22%
  8. Client 44: 95.23%
  9. Client 35: 95.26%
  10. Client 38: 95.27%

Communication Rounds:  26%|██▌       | 26/100 [1:00:34<2:39:22, 129.22s/round]

  ✓ 2/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 26 Summary:
   Median Test Accuracy: 95.57%
   Median Train Accuracy: 97.75%
   Std Dev: 0.14%
   Range: [95.24%, 95.90%]
   Weights Accepted: 13/50
   Weights Rejected: 37/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 27/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 44: 94.98%
  2. Client 14: 95.01%
  3. Client 39: 95.05%
  4. Client 16: 95.10%
  5. Client 34: 95.12%
  6. Client 50: 95.14%
  7. Client 19: 95.16%
  8. Client 9: 95.18%
  9. Client 43: 95.18%
  10. Client 27: 95.22%

Communication Rounds:  27%|██▋       | 27/100 [1:02:50<2:39:43, 131.28s/round]

Phase 3: Weight rejection decision...

📊 Round 27 Summary:
   Median Test Accuracy: 95.59%
   Median Train Accuracy: 97.71%
   Std Dev: 0.14%
   Range: [95.24%, 95.95%]
   Weights Accepted: 8/50
   Weights Rejected: 42/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 28/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 49: 94.94%
  2. Client 37: 94.99%
  3. Client 35: 95.00%
  4. Client 8: 95.12%
  5. Client 50: 95.16%
  6. Client 48: 95.18%
  7. Client 13: 95.19%
  8. Client 4: 95.20%
  9. Client 9: 95.20%
  10. Client 38: 95.21%

Communication Rounds:  28%|██▊       | 28/100 [1:05:04<2:38:35, 132.16s/round]

Phase 3: Weight rejection decision...

📊 Round 28 Summary:
   Median Test Accuracy: 95.60%
   Median Train Accuracy: 97.58%
   Std Dev: 0.15%
   Range: [95.24%, 95.95%]
   Weights Accepted: 10/50
   Weights Rejected: 40/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 29/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 18: 95.02%
  2. Client 16: 95.06%
  3. Client 5: 95.08%
  4. Client 9: 95.10%
  5. Client 40: 95.10%
  6. Client 48: 95.11%
  7. Client 46: 95.14%
  8. Client 21: 95.19%
  9. Client 8: 95.21%
  10. Client 41: 95.21%

Communication Rounds:  29%|██▉       | 29/100 [1:07:13<2:35:11, 131.14s/round]

  ✓ 1/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 29 Summary:
   Median Test Accuracy: 95.64%
   Median Train Accuracy: 97.67%
   Std Dev: 0.15%
   Range: [95.24%, 95.95%]
   Weights Accepted: 7/50
   Weights Rejected: 43/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 30/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 5: 94.87%
  2. Client 41: 94.88%
  3. Client 16: 94.91%
  4. Client 4: 95.03%
  5. Client 23: 95.09%
  6. Client 50: 95.10%
  7. Client 34: 95.16%
  8. Client 43: 95.22%
  9. Client 35: 95.25%
  10. Client 26: 95.26%

Communication Rounds:  30%|███       | 30/100 [1:09:28<2:34:12, 132.18s/round]

Phase 3: Weight rejection decision...

📊 Round 30 Summary:
   Median Test Accuracy: 95.65%
   Median Train Accuracy: 97.75%
   Std Dev: 0.14%
   Range: [95.29%, 95.95%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 31/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 4: 94.97%
  2. Client 7: 94.99%
  3. Client 14: 95.07%
  4. Client 34: 95.10%
  5. Client 6: 95.19%
  6. Client 39: 95.19%
  7. Client 33: 95.22%
  8. Client 36: 95.24%
  9. Client 15: 95.25%
  10. Client 49: 95.25%

Communication Rounds:  31%|███       | 31/100 [1:11:41<2:32:30, 132.62s/round]

Phase 3: Weight rejection decision...

📊 Round 31 Summary:
   Median Test Accuracy: 95.66%
   Median Train Accuracy: 97.75%
   Std Dev: 0.13%
   Range: [95.37%, 95.95%]
   Weights Accepted: 4/50
   Weights Rejected: 46/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 32/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 20: 94.96%
  2. Client 16: 95.05%
  3. Client 35: 95.17%
  4. Client 44: 95.17%
  5. Client 27: 95.23%
  6. Client 47: 95.23%
  7. Client 2: 95.24%
  8. Client 26: 95.24%
  9. Client 49: 95.26%
  10. Client 34: 95.28%

Communication Rounds:  32%|███▏      | 32/100 [1:13:58<2:31:43, 133.88s/round]

Phase 3: Weight rejection decision...

📊 Round 32 Summary:
   Median Test Accuracy: 95.68%
   Median Train Accuracy: 97.67%
   Std Dev: 0.14%
   Range: [95.37%, 95.95%]
   Weights Accepted: 7/50
   Weights Rejected: 43/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 33/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 22: 95.08%
  2. Client 35: 95.10%
  3. Client 37: 95.12%
  4. Client 50: 95.14%
  5. Client 23: 95.15%
  6. Client 30: 95.18%
  7. Client 4: 95.19%
  8. Client 20: 95.23%
  9. Client 9: 95.24%
  10. Client 26: 95.24%

Communication Rounds:  33%|███▎      | 33/100 [1:16:12<2:29:22, 133.77s/round]

Phase 3: Weight rejection decision...

📊 Round 33 Summary:
   Median Test Accuracy: 95.68%
   Median Train Accuracy: 97.63%
   Std Dev: 0.14%
   Range: [95.37%, 95.95%]
   Weights Accepted: 7/50
   Weights Rejected: 43/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 34/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 35: 94.99%
  2. Client 14: 95.13%
  3. Client 38: 95.14%
  4. Client 41: 95.18%
  5. Client 4: 95.23%
  6. Client 16: 95.23%
  7. Client 49: 95.29%
  8. Client 50: 95.30%
  9. Client 29: 95.33%
  10. Client 5: 95.36%

Communication Rounds:  34%|███▍      | 34/100 [1:18:27<2:27:47, 134.35s/round]

Phase 3: Weight rejection decision...

📊 Round 34 Summary:
   Median Test Accuracy: 95.68%
   Median Train Accuracy: 97.71%
   Std Dev: 0.14%
   Range: [95.38%, 95.95%]
   Weights Accepted: 7/50
   Weights Rejected: 43/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 35/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 14: 94.99%
  2. Client 40: 95.17%
  3. Client 43: 95.19%
  4. Client 26: 95.22%
  5. Client 49: 95.22%
  6. Client 15: 95.27%
  7. Client 4: 95.28%
  8. Client 23: 95.29%
  9. Client 37: 95.35%
  10. Client 44: 95.35%

Communication Rounds:  35%|███▌      | 35/100 [1:20:40<2:24:54, 133.77s/round]

Phase 3: Weight rejection decision...

📊 Round 35 Summary:
   Median Test Accuracy: 95.68%
   Median Train Accuracy: 97.75%
   Std Dev: 0.14%
   Range: [95.38%, 96.00%]
   Weights Accepted: 7/50
   Weights Rejected: 43/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 36/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 16: 95.04%
  2. Client 35: 95.09%
  3. Client 44: 95.14%
  4. Client 50: 95.22%
  5. Client 14: 95.29%
  6. Client 27: 95.32%
  7. Client 34: 95.32%
  8. Client 22: 95.34%
  9. Client 4: 95.35%
  10. Client 40: 95.36%

Communication Rounds:  36%|███▌      | 36/100 [1:22:55<2:23:07, 134.18s/round]

Phase 3: Weight rejection decision...

📊 Round 36 Summary:
   Median Test Accuracy: 95.68%
   Median Train Accuracy: 97.75%
   Std Dev: 0.15%
   Range: [95.38%, 96.05%]
   Weights Accepted: 7/50
   Weights Rejected: 43/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 37/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 20: 95.07%
  2. Client 35: 95.11%
  3. Client 23: 95.15%
  4. Client 46: 95.19%
  5. Client 4: 95.29%
  6. Client 16: 95.30%
  7. Client 27: 95.31%
  8. Client 13: 95.33%
  9. Client 40: 95.36%
  10. Client 41: 95.37%

Communication Rounds:  37%|███▋      | 37/100 [1:25:09<2:20:57, 134.24s/round]

Phase 3: Weight rejection decision...

📊 Round 37 Summary:
   Median Test Accuracy: 95.68%
   Median Train Accuracy: 97.71%
   Std Dev: 0.14%
   Range: [95.38%, 96.05%]
   Weights Accepted: 6/50
   Weights Rejected: 44/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 38/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 16: 94.89%
  2. Client 36: 95.14%
  3. Client 9: 95.18%
  4. Client 50: 95.20%
  5. Client 38: 95.21%
  6. Client 15: 95.32%
  7. Client 49: 95.33%
  8. Client 4: 95.35%
  9. Client 35: 95.35%
  10. Client 30: 95.36%

Communication Rounds:  38%|███▊      | 38/100 [1:27:24<2:18:48, 134.33s/round]

Phase 3: Weight rejection decision...

📊 Round 38 Summary:
   Median Test Accuracy: 95.70%
   Median Train Accuracy: 97.67%
   Std Dev: 0.14%
   Range: [95.38%, 96.05%]
   Weights Accepted: 10/50
   Weights Rejected: 40/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 39/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 35: 94.77%
  2. Client 49: 95.05%
  3. Client 26: 95.08%
  4. Client 38: 95.11%
  5. Client 36: 95.12%
  6. Client 1: 95.21%
  7. Client 3: 95.22%
  8. Client 27: 95.27%
  9. Client 41: 95.29%
  10. Client 44: 95.29%

Communication Rounds:  39%|███▉      | 39/100 [1:29:39<2:16:43, 134.49s/round]

Phase 3: Weight rejection decision...

📊 Round 39 Summary:
   Median Test Accuracy: 95.74%
   Median Train Accuracy: 97.67%
   Std Dev: 0.14%
   Range: [95.42%, 96.06%]
   Weights Accepted: 11/50
   Weights Rejected: 39/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 40/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 6: 95.06%
  2. Client 20: 95.08%
  3. Client 7: 95.13%
  4. Client 40: 95.14%
  5. Client 43: 95.16%
  6. Client 48: 95.16%
  7. Client 16: 95.17%
  8. Client 19: 95.25%
  9. Client 8: 95.27%
  10. Client 38: 95.27%

Communication Rounds:  40%|████      | 40/100 [1:31:47<2:12:28, 132.48s/round]

  ✓ 1/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 40 Summary:
   Median Test Accuracy: 95.76%
   Median Train Accuracy: 97.67%
   Std Dev: 0.14%
   Range: [95.42%, 96.06%]
   Weights Accepted: 5/50
   Weights Rejected: 45/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 41/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 35: 94.96%
  2. Client 36: 95.17%
  3. Client 4: 95.20%
  4. Client 50: 95.25%
  5. Client 3: 95.29%
  6. Client 46: 95.30%
  7. Client 38: 95.31%
  8. Client 44: 95.34%
  9. Client 43: 95.37%
  10. Client 22: 95.40%

Communication Rounds:  41%|████      | 41/100 [1:34:03<2:11:18, 133.54s/round]

Phase 3: Weight rejection decision...

📊 Round 41 Summary:
   Median Test Accuracy: 95.77%
   Median Train Accuracy: 97.67%
   Std Dev: 0.14%
   Range: [95.42%, 96.06%]
   Weights Accepted: 6/50
   Weights Rejected: 44/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 42/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 35: 95.10%
  2. Client 43: 95.16%
  3. Client 26: 95.19%
  4. Client 38: 95.24%
  5. Client 49: 95.26%
  6. Client 5: 95.35%
  7. Client 13: 95.35%
  8. Client 9: 95.36%
  9. Client 3: 95.42%
  10. Client 6: 95.42%

Communication Rounds:  42%|████▏     | 42/100 [1:36:16<2:09:09, 133.61s/round]

Phase 3: Weight rejection decision...

📊 Round 42 Summary:
   Median Test Accuracy: 95.78%
   Median Train Accuracy: 97.71%
   Std Dev: 0.14%
   Range: [95.46%, 96.06%]
   Weights Accepted: 4/50
   Weights Rejected: 46/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 43/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 23: 95.09%
  2. Client 13: 95.13%
  3. Client 27: 95.16%
  4. Client 4: 95.29%
  5. Client 9: 95.38%
  6. Client 35: 95.38%
  7. Client 39: 95.42%
  8. Client 44: 95.42%
  9. Client 49: 95.42%
  10. Client 16: 95.43%

Communication Rounds:  43%|████▎     | 43/100 [1:38:31<2:07:17, 134.00s/round]

Phase 3: Weight rejection decision...

📊 Round 43 Summary:
   Median Test Accuracy: 95.78%
   Median Train Accuracy: 97.75%
   Std Dev: 0.14%
   Range: [95.46%, 96.06%]
   Weights Accepted: 4/50
   Weights Rejected: 46/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 44/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 41: 95.01%
  2. Client 35: 95.15%
  3. Client 29: 95.25%
  4. Client 50: 95.26%
  5. Client 15: 95.30%
  6. Client 3: 95.31%
  7. Client 7: 95.32%
  8. Client 44: 95.33%
  9. Client 9: 95.43%
  10. Client 46: 95.43%

Communication Rounds:  44%|████▍     | 44/100 [1:40:44<2:04:46, 133.69s/round]

Phase 3: Weight rejection decision...

📊 Round 44 Summary:
   Median Test Accuracy: 95.78%
   Median Train Accuracy: 97.75%
   Std Dev: 0.13%
   Range: [95.46%, 96.06%]
   Weights Accepted: 5/50
   Weights Rejected: 45/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 45/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 7: 95.22%
  2. Client 44: 95.26%
  3. Client 41: 95.28%
  4. Client 4: 95.29%
  5. Client 23: 95.35%
  6. Client 9: 95.38%
  7. Client 30: 95.39%
  8. Client 50: 95.39%
  9. Client 48: 95.41%
  10. Client 3: 95.42%

Communication Rounds:  45%|████▌     | 45/100 [1:43:01<2:03:19, 134.53s/round]

Phase 3: Weight rejection decision...

📊 Round 45 Summary:
   Median Test Accuracy: 95.79%
   Median Train Accuracy: 97.58%
   Std Dev: 0.13%
   Range: [95.46%, 96.06%]
   Weights Accepted: 6/50
   Weights Rejected: 44/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 46/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 9: 95.14%
  2. Client 16: 95.14%
  3. Client 49: 95.17%
  4. Client 36: 95.18%
  5. Client 24: 95.20%
  6. Client 35: 95.27%
  7. Client 4: 95.34%
  8. Client 34: 95.36%
  9. Client 15: 95.41%
  10. Client 29: 95.42%

Communication Rounds:  46%|████▌     | 46/100 [1:45:16<2:01:08, 134.61s/round]

Phase 3: Weight rejection decision...

📊 Round 46 Summary:
   Median Test Accuracy: 95.79%
   Median Train Accuracy: 97.67%
   Std Dev: 0.13%
   Range: [95.46%, 96.06%]
   Weights Accepted: 9/50
   Weights Rejected: 41/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 47/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 9: 95.12%
  2. Client 35: 95.18%
  3. Client 38: 95.21%
  4. Client 50: 95.23%
  5. Client 29: 95.28%
  6. Client 26: 95.30%
  7. Client 41: 95.32%
  8. Client 4: 95.33%
  9. Client 44: 95.34%
  10. Client 23: 95.35%

Communication Rounds:  47%|████▋     | 47/100 [1:47:30<1:58:51, 134.55s/round]

Phase 3: Weight rejection decision...

📊 Round 47 Summary:
   Median Test Accuracy: 95.81%
   Median Train Accuracy: 97.63%
   Std Dev: 0.12%
   Range: [95.46%, 96.06%]
   Weights Accepted: 5/50
   Weights Rejected: 45/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 48/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 44: 95.22%
  2. Client 7: 95.35%
  3. Client 38: 95.39%
  4. Client 35: 95.42%
  5. Client 49: 95.42%
  6. Client 42: 95.43%
  7. Client 6: 95.44%
  8. Client 14: 95.44%
  9. Client 41: 95.51%
  10. Client 5: 95.52%

Communication Rounds:  48%|████▊     | 48/100 [1:49:44<1:56:33, 134.50s/round]

Phase 3: Weight rejection decision...

📊 Round 48 Summary:
   Median Test Accuracy: 95.81%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.53%, 96.06%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 49/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 49: 95.16%
  2. Client 4: 95.25%
  3. Client 29: 95.26%
  4. Client 35: 95.28%
  5. Client 38: 95.30%
  6. Client 39: 95.30%
  7. Client 43: 95.35%
  8. Client 44: 95.37%
  9. Client 23: 95.38%
  10. Client 26: 95.38%

Communication Rounds:  49%|████▉     | 49/100 [1:51:59<1:54:23, 134.57s/round]

Phase 3: Weight rejection decision...

📊 Round 49 Summary:
   Median Test Accuracy: 95.81%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.53%, 96.06%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 50/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 50: 95.12%
  2. Client 35: 95.14%
  3. Client 43: 95.16%
  4. Client 12: 95.22%
  5. Client 45: 95.43%
  6. Client 5: 95.44%
  7. Client 27: 95.44%
  8. Client 9: 95.45%
  9. Client 23: 95.45%
  10. Client 44: 95.46%

Communication Rounds:  50%|█████     | 50/100 [1:54:14<1:52:20, 134.82s/round]

Phase 3: Weight rejection decision...

📊 Round 50 Summary:
   Median Test Accuracy: 95.81%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.53%, 96.06%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 51/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 38: 95.26%
  2. Client 35: 95.28%
  3. Client 9: 95.34%
  4. Client 49: 95.34%
  5. Client 39: 95.35%
  6. Client 16: 95.39%
  7. Client 27: 95.39%
  8. Client 3: 95.43%
  9. Client 48: 95.44%
  10. Client 24: 95.49%

Communication Rounds:  51%|█████     | 51/100 [1:56:29<1:49:59, 134.68s/round]

Phase 3: Weight rejection decision...

📊 Round 51 Summary:
   Median Test Accuracy: 95.82%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.53%, 96.06%]
   Weights Accepted: 4/50
   Weights Rejected: 46/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 52/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 49: 95.07%
  2. Client 35: 95.12%
  3. Client 48: 95.13%
  4. Client 27: 95.26%
  5. Client 5: 95.27%
  6. Client 50: 95.30%
  7. Client 4: 95.31%
  8. Client 41: 95.31%
  9. Client 7: 95.33%
  10. Client 43: 95.36%

Communication Rounds:  52%|█████▏    | 52/100 [1:58:45<1:48:12, 135.26s/round]

Phase 3: Weight rejection decision...

📊 Round 52 Summary:
   Median Test Accuracy: 95.84%
   Median Train Accuracy: 97.71%
   Std Dev: 0.13%
   Range: [95.53%, 96.17%]
   Weights Accepted: 5/50
   Weights Rejected: 45/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 53/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 7: 95.19%
  2. Client 44: 95.23%
  3. Client 48: 95.25%
  4. Client 39: 95.26%
  5. Client 50: 95.42%
  6. Client 35: 95.43%
  7. Client 49: 95.43%
  8. Client 45: 95.44%
  9. Client 21: 95.46%
  10. Client 41: 95.46%

Communication Rounds:  53%|█████▎    | 53/100 [2:00:59<1:45:35, 134.80s/round]

Phase 3: Weight rejection decision...

📊 Round 53 Summary:
   Median Test Accuracy: 95.85%
   Median Train Accuracy: 97.75%
   Std Dev: 0.13%
   Range: [95.53%, 96.17%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 54/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 4: 95.06%
  2. Client 35: 95.14%
  3. Client 8: 95.25%
  4. Client 16: 95.48%
  5. Client 20: 95.50%
  6. Client 29: 95.50%
  7. Client 41: 95.50%
  8. Client 7: 95.52%
  9. Client 49: 95.52%
  10. Client 28: 95.53%

Communication Rounds:  54%|█████▍    | 54/100 [2:03:08<1:42:00, 133.05s/round]

  ✓ 1/10 clients improved with adaptive training

Phase 3: Weight rejection decision...

📊 Round 54 Summary:
   Median Test Accuracy: 95.85%
   Median Train Accuracy: 97.75%
   Std Dev: 0.13%
   Range: [95.53%, 96.17%]
   Weights Accepted: 6/50
   Weights Rejected: 44/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 55/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 23: 95.27%
  2. Client 35: 95.28%
  3. Client 27: 95.29%
  4. Client 20: 95.35%
  5. Client 7: 95.37%
  6. Client 38: 95.37%
  7. Client 41: 95.37%
  8. Client 37: 95.41%
  9. Client 50: 95.43%
  10. Client 21: 95.45%

Communication Rounds:  55%|█████▌    | 55/100 [2:05:23<1:40:11, 133.59s/round]

Phase 3: Weight rejection decision...

📊 Round 55 Summary:
   Median Test Accuracy: 95.85%
   Median Train Accuracy: 97.75%
   Std Dev: 0.13%
   Range: [95.54%, 96.17%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 56/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 9: 95.18%
  2. Client 7: 95.29%
  3. Client 49: 95.29%
  4. Client 35: 95.38%
  5. Client 23: 95.39%
  6. Client 16: 95.40%
  7. Client 27: 95.41%
  8. Client 13: 95.43%
  9. Client 29: 95.43%
  10. Client 40: 95.48%

Communication Rounds:  56%|█████▌    | 56/100 [2:07:38<1:38:12, 133.91s/round]

Phase 3: Weight rejection decision...

📊 Round 56 Summary:
   Median Test Accuracy: 95.85%
   Median Train Accuracy: 97.75%
   Std Dev: 0.13%
   Range: [95.54%, 96.17%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 57/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 4: 95.27%
  2. Client 45: 95.33%
  3. Client 27: 95.34%
  4. Client 13: 95.40%
  5. Client 15: 95.41%
  6. Client 26: 95.42%
  7. Client 34: 95.45%
  8. Client 19: 95.47%
  9. Client 25: 95.47%
  10. Client 23: 95.48%

Communication Rounds:  57%|█████▋    | 57/100 [2:09:53<1:36:17, 134.37s/round]

Phase 3: Weight rejection decision...

📊 Round 57 Summary:
   Median Test Accuracy: 95.87%
   Median Train Accuracy: 97.79%
   Std Dev: 0.12%
   Range: [95.58%, 96.17%]
   Weights Accepted: 6/50
   Weights Rejected: 44/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 58/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 49: 95.18%
  2. Client 50: 95.18%
  3. Client 9: 95.26%
  4. Client 35: 95.31%
  5. Client 16: 95.32%
  6. Client 7: 95.33%
  7. Client 3: 95.35%
  8. Client 48: 95.37%
  9. Client 5: 95.38%
  10. Client 29: 95.39%

Communication Rounds:  58%|█████▊    | 58/100 [2:12:06<1:33:47, 134.00s/round]

Phase 3: Weight rejection decision...

📊 Round 58 Summary:
   Median Test Accuracy: 95.88%
   Median Train Accuracy: 97.75%
   Std Dev: 0.12%
   Range: [95.58%, 96.17%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 59/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 11: 95.30%
  2. Client 27: 95.34%
  3. Client 35: 95.36%
  4. Client 16: 95.37%
  5. Client 20: 95.37%
  6. Client 2: 95.39%
  7. Client 7: 95.41%
  8. Client 8: 95.43%
  9. Client 9: 95.47%
  10. Client 44: 95.47%

Communication Rounds:  59%|█████▉    | 59/100 [2:14:23<1:32:06, 134.80s/round]

Phase 3: Weight rejection decision...

📊 Round 59 Summary:
   Median Test Accuracy: 95.88%
   Median Train Accuracy: 97.71%
   Std Dev: 0.12%
   Range: [95.58%, 96.17%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 60/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 43: 95.01%
  2. Client 16: 95.08%
  3. Client 45: 95.14%
  4. Client 7: 95.32%
  5. Client 29: 95.39%
  6. Client 34: 95.39%
  7. Client 39: 95.43%
  8. Client 36: 95.46%
  9. Client 23: 95.47%
  10. Client 6: 95.51%

Communication Rounds:  60%|██████    | 60/100 [2:16:43<1:30:53, 136.34s/round]

Phase 3: Weight rejection decision...

📊 Round 60 Summary:
   Median Test Accuracy: 95.89%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.58%, 96.17%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 61/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 9: 95.32%
  2. Client 12: 95.35%
  3. Client 18: 95.35%
  4. Client 41: 95.36%
  5. Client 21: 95.37%
  6. Client 43: 95.47%
  7. Client 6: 95.49%
  8. Client 27: 95.49%
  9. Client 37: 95.50%
  10. Client 16: 95.51%

Communication Rounds:  61%|██████    | 61/100 [2:18:59<1:28:39, 136.41s/round]

Phase 3: Weight rejection decision...

📊 Round 61 Summary:
   Median Test Accuracy: 95.89%
   Median Train Accuracy: 97.71%
   Std Dev: 0.12%
   Range: [95.58%, 96.17%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 62/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 44: 95.01%
  2. Client 14: 95.21%
  3. Client 16: 95.24%
  4. Client 46: 95.28%
  5. Client 50: 95.31%
  6. Client 42: 95.34%
  7. Client 7: 95.38%
  8. Client 26: 95.39%
  9. Client 8: 95.41%
  10. Client 49: 95.41%

Communication Rounds:  62%|██████▏   | 62/100 [2:21:14<1:26:04, 135.91s/round]

Phase 3: Weight rejection decision...

📊 Round 62 Summary:
   Median Test Accuracy: 95.89%
   Median Train Accuracy: 97.75%
   Std Dev: 0.12%
   Range: [95.58%, 96.17%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 63/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 27: 95.22%
  2. Client 7: 95.30%
  3. Client 4: 95.33%
  4. Client 35: 95.38%
  5. Client 20: 95.43%
  6. Client 45: 95.44%
  7. Client 29: 95.45%
  8. Client 38: 95.45%
  9. Client 24: 95.46%
  10. Client 23: 95.47%

Communication Rounds:  63%|██████▎   | 63/100 [2:23:29<1:23:36, 135.57s/round]

Phase 3: Weight rejection decision...

📊 Round 63 Summary:
   Median Test Accuracy: 95.89%
   Median Train Accuracy: 97.75%
   Std Dev: 0.12%
   Range: [95.60%, 96.17%]
   Weights Accepted: 8/50
   Weights Rejected: 42/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 64/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 16: 95.03%
  2. Client 6: 95.28%
  3. Client 11: 95.28%
  4. Client 8: 95.38%
  5. Client 38: 95.41%
  6. Client 4: 95.44%
  7. Client 7: 95.47%
  8. Client 9: 95.47%
  9. Client 43: 95.48%
  10. Client 26: 95.52%

Communication Rounds:  64%|██████▍   | 64/100 [2:25:44<1:21:19, 135.53s/round]

Phase 3: Weight rejection decision...

📊 Round 64 Summary:
   Median Test Accuracy: 95.89%
   Median Train Accuracy: 97.75%
   Std Dev: 0.12%
   Range: [95.60%, 96.17%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 65/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 43: 95.19%
  2. Client 49: 95.27%
  3. Client 35: 95.28%
  4. Client 3: 95.44%
  5. Client 39: 95.44%
  6. Client 7: 95.46%
  7. Client 44: 95.49%
  8. Client 9: 95.52%
  9. Client 18: 95.52%
  10. Client 23: 95.52%

Communication Rounds:  65%|██████▌   | 65/100 [2:27:59<1:18:54, 135.27s/round]

Phase 3: Weight rejection decision...

📊 Round 65 Summary:
   Median Test Accuracy: 95.89%
   Median Train Accuracy: 97.75%
   Std Dev: 0.12%
   Range: [95.61%, 96.20%]
   Weights Accepted: 5/50
   Weights Rejected: 45/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 66/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 41: 94.88%
  2. Client 7: 95.04%
  3. Client 11: 95.24%
  4. Client 37: 95.35%
  5. Client 38: 95.38%
  6. Client 44: 95.39%
  7. Client 27: 95.45%
  8. Client 50: 95.45%
  9. Client 15: 95.47%
  10. Client 5: 95.49%

Communication Rounds:  66%|██████▌   | 66/100 [2:30:15<1:16:44, 135.43s/round]

Phase 3: Weight rejection decision...

📊 Round 66 Summary:
   Median Test Accuracy: 95.90%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.61%, 96.20%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 67/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 4: 95.13%
  2. Client 7: 95.29%
  3. Client 38: 95.36%
  4. Client 34: 95.41%
  5. Client 49: 95.42%
  6. Client 20: 95.45%
  7. Client 23: 95.45%
  8. Client 5: 95.46%
  9. Client 8: 95.47%
  10. Client 25: 95.48%

Communication Rounds:  67%|██████▋   | 67/100 [2:32:28<1:14:05, 134.71s/round]

Phase 3: Weight rejection decision...

📊 Round 67 Summary:
   Median Test Accuracy: 95.90%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 68/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 16: 95.32%
  2. Client 37: 95.35%
  3. Client 26: 95.39%
  4. Client 44: 95.43%
  5. Client 7: 95.45%
  6. Client 9: 95.45%
  7. Client 35: 95.48%
  8. Client 43: 95.48%
  9. Client 18: 95.49%
  10. Client 6: 95.52%

Communication Rounds:  68%|██████▊   | 68/100 [2:34:44<1:12:06, 135.19s/round]

Phase 3: Weight rejection decision...

📊 Round 68 Summary:
   Median Test Accuracy: 95.90%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 5/50
   Weights Rejected: 45/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 69/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 8: 95.09%
  2. Client 44: 95.16%
  3. Client 35: 95.31%
  4. Client 26: 95.35%
  5. Client 37: 95.36%
  6. Client 23: 95.39%
  7. Client 22: 95.41%
  8. Client 39: 95.42%
  9. Client 43: 95.42%
  10. Client 16: 95.45%

Communication Rounds:  69%|██████▉   | 69/100 [2:36:59<1:09:43, 134.96s/round]

Phase 3: Weight rejection decision...

📊 Round 69 Summary:
   Median Test Accuracy: 95.90%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 1/50
   Weights Rejected: 49/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 70/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 49: 95.18%
  2. Client 35: 95.21%
  3. Client 37: 95.38%
  4. Client 4: 95.40%
  5. Client 3: 95.45%
  6. Client 11: 95.46%
  7. Client 7: 95.49%
  8. Client 44: 95.51%
  9. Client 39: 95.52%
  10. Client 9: 95.54%

Communication Rounds:  70%|███████   | 70/100 [2:39:14<1:07:31, 135.06s/round]

Phase 3: Weight rejection decision...

📊 Round 70 Summary:
   Median Test Accuracy: 95.92%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 5/50
   Weights Rejected: 45/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 71/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 7: 95.12%
  2. Client 35: 95.43%
  3. Client 23: 95.45%
  4. Client 34: 95.47%
  5. Client 41: 95.48%
  6. Client 44: 95.51%
  7. Client 49: 95.52%
  8. Client 3: 95.54%
  9. Client 9: 95.54%
  10. Client 22: 95.56%

Communication Rounds:  71%|███████   | 71/100 [2:41:30<1:05:24, 135.31s/round]

Phase 3: Weight rejection decision...

📊 Round 71 Summary:
   Median Test Accuracy: 95.93%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 5/50
   Weights Rejected: 45/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 72/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 4: 95.15%
  2. Client 7: 95.21%
  3. Client 46: 95.22%
  4. Client 22: 95.25%
  5. Client 37: 95.26%
  6. Client 44: 95.26%
  7. Client 9: 95.28%
  8. Client 5: 95.40%
  9. Client 35: 95.42%
  10. Client 13: 95.44%

Communication Rounds:  72%|███████▏  | 72/100 [2:43:44<1:03:00, 135.01s/round]

Phase 3: Weight rejection decision...

📊 Round 72 Summary:
   Median Test Accuracy: 95.93%
   Median Train Accuracy: 97.71%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 73/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 50: 95.41%
  2. Client 9: 95.44%
  3. Client 27: 95.46%
  4. Client 16: 95.47%
  5. Client 37: 95.52%
  6. Client 45: 95.54%
  7. Client 46: 95.55%
  8. Client 3: 95.56%
  9. Client 26: 95.57%
  10. Client 6: 95.58%

Communication Rounds:  73%|███████▎  | 73/100 [2:45:59<1:00:48, 135.12s/round]

Phase 3: Weight rejection decision...

📊 Round 73 Summary:
   Median Test Accuracy: 95.93%
   Median Train Accuracy: 97.71%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 1/50
   Weights Rejected: 49/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 74/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 26: 95.16%
  2. Client 44: 95.40%
  3. Client 29: 95.42%
  4. Client 15: 95.44%
  5. Client 3: 95.47%
  6. Client 35: 95.47%
  7. Client 33: 95.49%
  8. Client 48: 95.49%
  9. Client 40: 95.52%
  10. Client 7: 95.53%

Communication Rounds:  74%|███████▍  | 74/100 [2:48:12<58:15, 134.44s/round]

Phase 3: Weight rejection decision...

📊 Round 74 Summary:
   Median Test Accuracy: 95.93%
   Median Train Accuracy: 97.79%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 4/50
   Weights Rejected: 46/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 75/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 36: 95.12%
  2. Client 14: 95.19%
  3. Client 4: 95.25%
  4. Client 16: 95.33%
  5. Client 34: 95.38%
  6. Client 35: 95.47%
  7. Client 41: 95.47%
  8. Client 43: 95.48%
  9. Client 5: 95.51%
  10. Client 18: 95.53%

Communication Rounds:  75%|███████▌  | 75/100 [2:50:29<56:15, 135.01s/round]

Phase 3: Weight rejection decision...

📊 Round 75 Summary:
   Median Test Accuracy: 95.94%
   Median Train Accuracy: 97.79%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 76/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 35: 95.24%
  2. Client 38: 95.27%
  3. Client 7: 95.39%
  4. Client 9: 95.40%
  5. Client 50: 95.42%
  6. Client 41: 95.43%
  7. Client 48: 95.43%
  8. Client 44: 95.46%
  9. Client 4: 95.48%
  10. Client 15: 95.52%

Communication Rounds:  76%|███████▌  | 76/100 [2:52:42<53:45, 134.40s/round]

Phase 3: Weight rejection decision...

📊 Round 76 Summary:
   Median Test Accuracy: 95.94%
   Median Train Accuracy: 97.83%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 77/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 44: 95.19%
  2. Client 27: 95.33%
  3. Client 24: 95.44%
  4. Client 35: 95.44%
  5. Client 39: 95.45%
  6. Client 4: 95.49%
  7. Client 13: 95.49%
  8. Client 49: 95.49%
  9. Client 3: 95.50%
  10. Client 45: 95.50%

Communication Rounds:  77%|███████▋  | 77/100 [2:54:58<51:41, 134.87s/round]

Phase 3: Weight rejection decision...

📊 Round 77 Summary:
   Median Test Accuracy: 95.95%
   Median Train Accuracy: 97.79%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 78/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 50: 95.12%
  2. Client 38: 95.13%
  3. Client 9: 95.14%
  4. Client 5: 95.16%
  5. Client 7: 95.21%
  6. Client 35: 95.23%
  7. Client 43: 95.24%
  8. Client 4: 95.27%
  9. Client 26: 95.35%
  10. Client 14: 95.46%

Communication Rounds:  78%|███████▊  | 78/100 [2:57:12<49:26, 134.82s/round]

Phase 3: Weight rejection decision...

📊 Round 78 Summary:
   Median Test Accuracy: 95.95%
   Median Train Accuracy: 97.75%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 4/50
   Weights Rejected: 46/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 79/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 26: 95.24%
  2. Client 35: 95.25%
  3. Client 48: 95.26%
  4. Client 36: 95.42%
  5. Client 23: 95.47%
  6. Client 4: 95.49%
  7. Client 12: 95.49%
  8. Client 44: 95.49%
  9. Client 24: 95.50%
  10. Client 41: 95.50%

Communication Rounds:  79%|███████▉  | 79/100 [2:59:27<47:08, 134.70s/round]

Phase 3: Weight rejection decision...

📊 Round 79 Summary:
   Median Test Accuracy: 95.95%
   Median Train Accuracy: 97.75%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 0/50
   Weights Rejected: 50/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 80/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 18: 95.31%
  2. Client 44: 95.37%
  3. Client 48: 95.41%
  4. Client 9: 95.43%
  5. Client 27: 95.44%
  6. Client 11: 95.50%
  7. Client 43: 95.50%
  8. Client 49: 95.51%
  9. Client 7: 95.52%
  10. Client 8: 95.52%

Communication Rounds:  80%|████████  | 80/100 [3:01:42<44:57, 134.85s/round]

Phase 3: Weight rejection decision...

📊 Round 80 Summary:
   Median Test Accuracy: 95.95%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 4/50
   Weights Rejected: 46/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 81/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 40: 95.01%
  2. Client 7: 95.20%
  3. Client 38: 95.42%
  4. Client 44: 95.43%
  5. Client 8: 95.45%
  6. Client 48: 95.49%
  7. Client 5: 95.50%
  8. Client 11: 95.50%
  9. Client 25: 95.51%
  10. Client 45: 95.51%

Communication Rounds:  81%|████████  | 81/100 [3:03:56<42:35, 134.47s/round]

Phase 3: Weight rejection decision...

📊 Round 81 Summary:
   Median Test Accuracy: 95.96%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.21%]
   Weights Accepted: 5/50
   Weights Rejected: 45/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 82/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 24: 95.27%
  2. Client 8: 95.28%
  3. Client 9: 95.30%
  4. Client 4: 95.31%
  5. Client 40: 95.39%
  6. Client 27: 95.46%
  7. Client 16: 95.48%
  8. Client 35: 95.48%
  9. Client 46: 95.49%
  10. Client 36: 95.50%

Communication Rounds:  82%|████████▏ | 82/100 [3:06:11<40:28, 134.91s/round]

Phase 3: Weight rejection decision...

📊 Round 82 Summary:
   Median Test Accuracy: 95.96%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.22%]
   Weights Accepted: 4/50
   Weights Rejected: 46/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 83/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 27: 94.99%
  2. Client 16: 95.15%
  3. Client 44: 95.26%
  4. Client 7: 95.28%
  5. Client 20: 95.41%
  6. Client 22: 95.44%
  7. Client 5: 95.53%
  8. Client 14: 95.53%
  9. Client 43: 95.53%
  10. Client 12: 95.56%

Communication Rounds:  83%|████████▎ | 83/100 [3:08:25<38:05, 134.46s/round]

Phase 3: Weight rejection decision...

📊 Round 83 Summary:
   Median Test Accuracy: 95.97%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.22%]
   Weights Accepted: 1/50
   Weights Rejected: 49/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 84/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 35: 95.16%
  2. Client 26: 95.19%
  3. Client 14: 95.47%
  4. Client 39: 95.50%
  5. Client 29: 95.53%
  6. Client 44: 95.54%
  7. Client 37: 95.55%
  8. Client 45: 95.57%
  9. Client 11: 95.58%
  10. Client 5: 95.59%

Communication Rounds:  84%|████████▍ | 84/100 [3:10:41<36:00, 135.05s/round]

Phase 3: Weight rejection decision...

📊 Round 84 Summary:
   Median Test Accuracy: 95.97%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.22%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 85/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 8: 95.23%
  2. Client 9: 95.35%
  3. Client 35: 95.43%
  4. Client 23: 95.49%
  5. Client 18: 95.52%
  6. Client 41: 95.52%
  7. Client 7: 95.54%
  8. Client 44: 95.54%
  9. Client 14: 95.55%
  10. Client 16: 95.56%

Communication Rounds:  85%|████████▌ | 85/100 [3:12:55<33:41, 134.74s/round]

Phase 3: Weight rejection decision...

📊 Round 85 Summary:
   Median Test Accuracy: 95.98%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.22%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 86/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 20: 95.11%
  2. Client 9: 95.26%
  3. Client 27: 95.33%
  4. Client 16: 95.36%
  5. Client 41: 95.40%
  6. Client 49: 95.40%
  7. Client 34: 95.45%
  8. Client 43: 95.45%
  9. Client 38: 95.48%
  10. Client 35: 95.49%

Communication Rounds:  86%|████████▌ | 86/100 [3:15:12<31:33, 135.23s/round]

Phase 3: Weight rejection decision...

📊 Round 86 Summary:
   Median Test Accuracy: 95.98%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.22%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 87/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 15: 95.22%
  2. Client 3: 95.42%
  3. Client 35: 95.43%
  4. Client 38: 95.48%
  5. Client 44: 95.49%
  6. Client 43: 95.52%
  7. Client 49: 95.52%
  8. Client 48: 95.54%
  9. Client 45: 95.57%
  10. Client 8: 95.59%

Communication Rounds:  87%|████████▋ | 87/100 [3:17:27<29:18, 135.28s/round]

Phase 3: Weight rejection decision...

📊 Round 87 Summary:
   Median Test Accuracy: 95.98%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.22%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 88/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 35: 94.97%
  2. Client 38: 95.22%
  3. Client 23: 95.36%
  4. Client 14: 95.44%
  5. Client 8: 95.46%
  6. Client 42: 95.46%
  7. Client 43: 95.47%
  8. Client 47: 95.52%
  9. Client 4: 95.53%
  10. Client 3: 95.55%

Communication Rounds:  88%|████████▊ | 88/100 [3:19:41<26:59, 135.00s/round]

Phase 3: Weight rejection decision...

📊 Round 88 Summary:
   Median Test Accuracy: 95.98%
   Median Train Accuracy: 97.67%
   Std Dev: 0.12%
   Range: [95.67%, 96.22%]
   Weights Accepted: 1/50
   Weights Rejected: 49/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 89/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 27: 95.26%
  2. Client 35: 95.28%
  3. Client 44: 95.35%
  4. Client 43: 95.37%
  5. Client 9: 95.52%
  6. Client 38: 95.55%
  7. Client 40: 95.58%
  8. Client 41: 95.58%
  9. Client 18: 95.59%
  10. Client 5: 95.61%

Communication Rounds:  89%|████████▉ | 89/100 [3:21:58<24:49, 135.37s/round]

Phase 3: Weight rejection decision...

📊 Round 89 Summary:
   Median Test Accuracy: 95.98%
   Median Train Accuracy: 97.75%
   Std Dev: 0.12%
   Range: [95.67%, 96.22%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 90/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 43: 95.05%
  2. Client 14: 95.35%
  3. Client 26: 95.38%
  4. Client 15: 95.50%
  5. Client 34: 95.50%
  6. Client 35: 95.50%
  7. Client 16: 95.51%
  8. Client 7: 95.52%
  9. Client 50: 95.52%
  10. Client 27: 95.53%

Communication Rounds:  90%|█████████ | 90/100 [3:24:12<22:29, 134.98s/round]

Phase 3: Weight rejection decision...

📊 Round 90 Summary:
   Median Test Accuracy: 95.99%
   Median Train Accuracy: 97.79%
   Std Dev: 0.12%
   Range: [95.67%, 96.30%]
   Weights Accepted: 4/50
   Weights Rejected: 46/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 91/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 43: 95.15%
  2. Client 38: 95.37%
  3. Client 27: 95.39%
  4. Client 18: 95.42%
  5. Client 11: 95.47%
  6. Client 30: 95.52%
  7. Client 17: 95.53%
  8. Client 13: 95.54%
  9. Client 16: 95.55%
  10. Client 24: 95.55%

Communication Rounds:  91%|█████████ | 91/100 [3:26:29<20:19, 135.53s/round]

Phase 3: Weight rejection decision...

📊 Round 91 Summary:
   Median Test Accuracy: 95.99%
   Median Train Accuracy: 97.83%
   Std Dev: 0.12%
   Range: [95.67%, 96.30%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 92/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 13: 95.23%
  2. Client 49: 95.30%
  3. Client 5: 95.31%
  4. Client 4: 95.43%
  5. Client 32: 95.45%
  6. Client 43: 95.45%
  7. Client 38: 95.50%
  8. Client 50: 95.52%
  9. Client 45: 95.53%
  10. Client 9: 95.55%

Communication Rounds:  92%|█████████▏| 92/100 [3:28:43<18:00, 135.12s/round]

Phase 3: Weight rejection decision...

📊 Round 92 Summary:
   Median Test Accuracy: 95.99%
   Median Train Accuracy: 97.83%
   Std Dev: 0.12%
   Range: [95.67%, 96.30%]
   Weights Accepted: 0/50
   Weights Rejected: 50/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 93/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 39: 95.13%
  2. Client 26: 95.26%
  3. Client 7: 95.28%
  4. Client 27: 95.37%
  5. Client 21: 95.38%
  6. Client 8: 95.42%
  7. Client 35: 95.42%
  8. Client 43: 95.50%
  9. Client 49: 95.51%
  10. Client 41: 95.58%

Communication Rounds:  93%|█████████▎| 93/100 [3:30:59<15:48, 135.55s/round]

Phase 3: Weight rejection decision...

📊 Round 93 Summary:
   Median Test Accuracy: 95.99%
   Median Train Accuracy: 97.83%
   Std Dev: 0.12%
   Range: [95.67%, 96.30%]
   Weights Accepted: 0/50
   Weights Rejected: 50/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 94/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 7: 95.33%
  2. Client 43: 95.36%
  3. Client 34: 95.38%
  4. Client 48: 95.40%
  5. Client 9: 95.45%
  6. Client 18: 95.50%
  7. Client 41: 95.52%
  8. Client 20: 95.53%
  9. Client 5: 95.55%
  10. Client 39: 95.55%

Communication Rounds:  94%|█████████▍| 94/100 [3:33:14<13:32, 135.39s/round]

Phase 3: Weight rejection decision...

📊 Round 94 Summary:
   Median Test Accuracy: 95.99%
   Median Train Accuracy: 97.83%
   Std Dev: 0.12%
   Range: [95.67%, 96.30%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 95/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 7: 95.28%
  2. Client 38: 95.41%
  3. Client 27: 95.42%
  4. Client 16: 95.43%
  5. Client 14: 95.46%
  6. Client 30: 95.46%
  7. Client 44: 95.50%
  8. Client 49: 95.51%
  9. Client 15: 95.53%
  10. Client 40: 95.53%

Communication Rounds:  95%|█████████▌| 95/100 [3:35:30<11:17, 135.40s/round]

Phase 3: Weight rejection decision...

📊 Round 95 Summary:
   Median Test Accuracy: 96.00%
   Median Train Accuracy: 97.83%
   Std Dev: 0.12%
   Range: [95.71%, 96.30%]
   Weights Accepted: 5/50
   Weights Rejected: 45/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 96/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 43: 95.16%
  2. Client 7: 95.28%
  3. Client 35: 95.34%
  4. Client 15: 95.35%
  5. Client 1: 95.36%
  6. Client 34: 95.36%
  7. Client 16: 95.40%
  8. Client 9: 95.46%
  9. Client 40: 95.48%
  10. Client 5: 95.49%

Communication Rounds:  96%|█████████▌| 96/100 [3:37:45<09:01, 135.35s/round]

Phase 3: Weight rejection decision...

📊 Round 96 Summary:
   Median Test Accuracy: 96.00%
   Median Train Accuracy: 97.92%
   Std Dev: 0.12%
   Range: [95.71%, 96.30%]
   Weights Accepted: 2/50
   Weights Rejected: 48/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 97/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 4: 95.32%
  2. Client 41: 95.33%
  3. Client 5: 95.39%
  4. Client 44: 95.40%
  5. Client 22: 95.44%
  6. Client 27: 95.45%
  7. Client 9: 95.49%
  8. Client 35: 95.51%
  9. Client 1: 95.52%
  10. Client 15: 95.53%

Communication Rounds:  97%|█████████▋| 97/100 [3:40:00<06:45, 135.15s/round]

Phase 3: Weight rejection decision...

📊 Round 97 Summary:
   Median Test Accuracy: 96.00%
   Median Train Accuracy: 97.92%
   Std Dev: 0.12%
   Range: [95.71%, 96.30%]
   Weights Accepted: 1/50
   Weights Rejected: 49/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 98/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 22: 95.45%
  2. Client 43: 95.45%
  3. Client 26: 95.47%
  4. Client 36: 95.47%
  5. Client 44: 95.48%
  6. Client 9: 95.49%
  7. Client 16: 95.50%
  8. Client 38: 95.50%
  9. Client 50: 95.56%
  10. Client 40: 95.57%

Communication Rounds:  98%|█████████▊| 98/100 [3:42:16<04:30, 135.39s/round]

Phase 3: Weight rejection decision...

📊 Round 98 Summary:
   Median Test Accuracy: 96.00%
   Median Train Accuracy: 97.92%
   Std Dev: 0.13%
   Range: [95.71%, 96.30%]
   Weights Accepted: 1/50
   Weights Rejected: 49/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 99/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 43: 95.07%
  2. Client 35: 95.17%
  3. Client 36: 95.46%
  4. Client 3: 95.49%
  5. Client 41: 95.54%
  6. Client 42: 95.54%
  7. Client 22: 95.55%
  8. Client 18: 95.57%
  9. Client 40: 95.57%
  10. Client 9: 95.59%

Communication Rounds:  99%|█████████▉| 99/100 [3:44:29<02:14, 134.90s/round]

Phase 3: Weight rejection decision...

📊 Round 99 Summary:
   Median Test Accuracy: 96.01%
   Median Train Accuracy: 97.83%
   Std Dev: 0.12%
   Range: [95.71%, 96.30%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
ROUND 100/100
======================================================================

Phase 1: Training all 50 clients for 10 epochs...

Phase 2: Adaptive training for bottom 10 clients...
Bottom 10 clients identified:
  1. Client 16: 95.10%
  2. Client 23: 95.23%
  3. Client 44: 95.30%
  4. Client 43: 95.34%
  5. Client 35: 95.36%
  6. Client 8: 95.41%
  7. Client 9: 95.42%
  8. Client 49: 95.50%
  9. Client 4: 95.56%
  10. Client 7: 95.56%

Communication Rounds: 100%|██████████| 100/100 [3:46:47<00:00, 136.08s/round]

Phase 3: Weight rejection decision...

📊 Round 100 Summary:
   Median Test Accuracy: 96.01%
   Median Train Accuracy: 97.88%
   Std Dev: 0.12%
   Range: [95.71%, 96.30%]
   Weights Accepted: 3/50
   Weights Rejected: 47/50
   Adaptive Training: 10/50 clients

======================================================================
FEDERATED TRAINING COMPLETE!
======================================================================

## Results Analysis

In [10]:
# Calculate final statistics
final_test_accs = [client_test_acc_history[i][-1] * 100 for i in range(NUM_CLIENTS)]
final_train_accs = [client_train_acc_history[i][-1] * 100 for i in range(NUM_CLIENTS)]
total_rejections_per_client = [sum(client_rejections[i]) for i in range(NUM_CLIENTS)]
total_epochs_per_client = [sum(client_epochs_used[i]) for i in range(NUM_CLIENTS)]
total_adaptive_rounds = [sum(client_adaptive_rounds[i]) for i in range(NUM_CLIENTS)]

print("=" * 70)
print("FINAL RESULTS")
print("=" * 70)
print(f"Median Final Test Accuracy: {np.median(final_test_accs):.2f}%")
print(f"Median Final Train Accuracy: {np.median(final_train_accs):.2f}%")
print(f"Std Dev (Test): {np.std(final_test_accs):.2f}%")
print(f"Std Dev (Train): {np.std(final_train_accs):.2f}%")
print(f"Test Accuracy Range: [{np.min(final_test_accs):.2f}%, {np.max(final_test_accs):.2f}%]")
print(f"Train Accuracy Range: [{np.min(final_train_accs):.2f}%, {np.max(final_train_accs):.2f}%]")
print()
print("Weight Rejection Statistics:")
print(f"  Total Rejections: {sum(total_rejections_per_client)} / {NUM_CLIENTS * NUM_ROUNDS}")
print(f"  Rejection Rate: {sum(total_rejections_per_client) / (NUM_CLIENTS * NUM_ROUNDS) * 100:.2f}%")
print(f"  Median Rejections per Client: {np.median(total_rejections_per_client):.2f}")
print()
print("Adaptive Training Statistics:")
print(f"  Total Adaptive Rounds: {sum(total_adaptive_rounds)}")
print(f"  Median Adaptive Rounds per Client: {np.median(total_adaptive_rounds):.2f}")
print(f"  Total Epochs Used: {sum(total_epochs_per_client)}")
print(f"  Median Epochs per Client: {np.median(total_epochs_per_client):.1f}")
print("=" * 70 + "\n")

======================================================================
FINAL RESULTS
======================================================================
Median Final Test Accuracy: 96.01%
Median Final Train Accuracy: 97.88%
Std Dev (Test): 0.12%
Std Dev (Train): 0.48%
Test Accuracy Range: [95.71%, 96.30%]
Train Accuracy Range: [96.83%, 98.75%]

Weight Rejection Statistics:
  Total Rejections: 3963 / 5000
  Rejection Rate: 79.26%
  Median Rejections per Client: 80.00

Adaptive Training Statistics:
  Total Adaptive Rounds: 913
  Median Adaptive Rounds per Client: 16.00
  Total Epochs Used: 85850
  Median Epochs per Client: 1622.5
======================================================================

In [11]:
# Detailed per-client results
print("PER-CLIENT RESULTS:")
print("-" * 128)
print(f"{'Client':<8} {'Final Test':<12} {'Final Train':<12} {'Total Epochs':<14} {'Rejections':<14} {'Adaptive Rounds':<16}")
print("-" * 128)

for client_id in range(NUM_CLIENTS):
    final_test = final_test_accs[client_id]
    final_train = final_train_accs[client_id]
    total_epochs = total_epochs_per_client[client_id]
    rejections = total_rejections_per_client[client_id]
    adaptive = total_adaptive_rounds[client_id]
    print(f"{client_id + 1:<8} {final_test:.2f}%{'':<6} {final_train:.2f}%{'':<6} {total_epochs:<14} {rejections:<14} {adaptive:<16}")

print("-" * 128 + "\n")

PER-CLIENT RESULTS:
--------------------------------------------------------------------------------------------------------------------------------
Client   Final Test   Final Train  Total Epochs   Rejections     Adaptive Rounds
--------------------------------------------------------------------------------------------------------------------------------
1        96.05%       96.92%       1120           80             3
2        96.08%       97.92%       1125           78             4
3        95.99%       98.42%       1840           80             21
4        95.88%       98.00%       2650           81             42
5        95.88%       97.25%       1925           81             24
6        96.10%       97.50%       1360           78             9
7        95.95%       98.25%       2765           80             45
8        96.02%       97.42%       2055           78             28
9        95.92%       98.25%       2950           77             51
10       96.20%       97.75%       1000           78             0
11       96.08%       97.67%       1360           80             9
12       96.05%       98.00%       1160           81             4
13       96.09%       98.08%       1440           81             11
14       95.97%       97.67%       1640           82             16
15       95.89%       98.42%       1640           83             16
16       95.85%       97.17%       2765           72             45
17       96.30%       97.75%       1040           79             1
18       96.12%       97.67%       1480           80             12
19       96.13%       97.83%       1240           79             6
20       96.15%       98.50%       1680           83             17
21       96.08%       98.75%       1280           79             7
22       96.08%       98.25%       1440           81             11
23       95.89%       98.42%       1970           78             25
24       95.88%       98.17%       1360           79             9
25       96.17%       98.33%       1120           75             3
26       95.92%       97.17%       1960           76             24
27       95.93%       98.33%       2120           81             28
28       96.21%       96.92%       1005           75             1
29       95.85%       98.00%       1645           78             17
30       95.99%       97.67%       1240           80             6
31       96.16%       98.08%       1000           80             0
32       96.17%       98.00%       1040           79             1
33       96.09%       97.25%       1165           80             5
34       95.99%       97.33%       1720           80             18
35       95.71%       98.00%       3520           84             63
36       96.07%       98.17%       1520           77             13
37       95.95%       96.83%       1640           76             16
38       95.89%       97.67%       2440           82             36
39       96.00%       97.33%       1725           80             19
40       96.02%       98.08%       1605           75             16
41       95.87%       97.42%       2170           75             31
42       96.04%       97.83%       1200           79             5
43       95.85%       97.67%       2520           83             38
44       95.83%       97.58%       2920           80             48
45       96.01%       98.25%       1560           76             14
46       96.01%       97.83%       1480           82             12
47       96.21%       97.50%       1080           83             2
48       95.96%       98.58%       1680           75             17
49       95.80%       98.75%       2410           84             37
50       96.07%       98.42%       2080           80             27
--------------------------------------------------------------------------------------------------------------------------------

## Round-wise Accuracy Tables

In [12]:
# Create client x round tables for test and training accuracy
TARGET_ROUNDS = 100
available_rounds = len(client_test_acc_history[0])
num_table_rounds = min(TARGET_ROUNDS, available_rounds)

client_labels = [f"Client_{i+1}" for i in range(NUM_CLIENTS)]
round_labels = [f"Round_{r+1}" for r in range(num_table_rounds)]

test_matrix = np.array([hist[:num_table_rounds] for hist in client_test_acc_history]) * 100
train_matrix = np.array([hist[:num_table_rounds] for hist in client_train_acc_history]) * 100

test_acc_table = pd.DataFrame(test_matrix, index=client_labels, columns=round_labels)
train_acc_table = pd.DataFrame(train_matrix, index=client_labels, columns=round_labels)

# Save as CSV for full inspection in spreadsheet tools
test_csv_path = f'{RESULTS_DIR}/test_accuracy_client_round_table_{num_table_rounds}_rounds.csv'
train_csv_path = f'{RESULTS_DIR}/train_accuracy_client_round_table_{num_table_rounds}_rounds.csv'
test_acc_table.to_csv(test_csv_path, index=True)
train_acc_table.to_csv(train_csv_path, index=True)

print("=" * 70)
print("CLIENT x ROUND ACCURACY TABLES")
print("=" * 70)
print(f"Rows (clients): {test_acc_table.shape[0]}")
print(f"Columns (rounds): {test_acc_table.shape[1]}")
print(f"Target rounds requested: {TARGET_ROUNDS}")
print(f"Rounds available from current run: {available_rounds}")
print(f"Using rounds in table: {num_table_rounds}")
print()
print(f"✓ Test accuracy table saved: {test_csv_path}")
print(f"✓ Train accuracy table saved: {train_csv_path}")
print()
print("Test accuracy table (first 5 clients, first 10 rounds):")
display(test_acc_table.iloc[:5, :10])
print("\nTrain accuracy table (first 5 clients, first 10 rounds):")
display(train_acc_table.iloc[:5, :10])
print("=" * 70)

======================================================================
CLIENT x ROUND ACCURACY TABLES
======================================================================
Rows (clients): 50
Columns (rounds): 100
Target rounds requested: 100
Rounds available from current run: 100
Using rounds in table: 100

✓ Test accuracy table saved: results_adaptive_weight_rejection_60_per_class_50_clients/test_accuracy_client_round_table_100_rounds.csv
✓ Train accuracy table saved: results_adaptive_weight_rejection_60_per_class_50_clients/train_accuracy_client_round_table_100_rounds.csv

Test accuracy table (first 5 clients, first 10 rounds):

,Round_1,Round_2,Round_3,Round_4,Round_5,Round_6,Round_7,Round_8,Round_9,Round_10
Client_1,89.980000,91.360003,92.490000,93.750000,93.800002,94.389999,94.809997,94.970000,94.970000,95.209998
Client_2,88.849998,90.549999,92.320001,93.260002,93.400002,94.169998,94.550002,94.639999,94.690001,94.959998
Client_3,89.870000,91.500002,92.339998,93.169999,93.279999,93.930000,94.510001,94.510001,94.630003,94.630003
Client_4,89.440000,91.610003,92.479998,93.400002,93.800002,94.349998,94.349998,94.410002,94.739997,94.739997
Client_5,90.120000,91.360003,92.610002,93.580002,93.660003,94.010001,94.389999,94.410002,94.819999,94.819999

Train accuracy table (first 5 clients, first 10 rounds):

,Round_1,Round_2,Round_3,Round_4,Round_5,Round_6,Round_7,Round_8,Round_9,Round_10
Client_1,86.416668,91.666669,93.750000,94.999999,94.749999,96.416664,95.583332,95.916665,95.916665,97.333336
Client_2,87.666667,92.166668,94.499999,95.166665,95.166665,95.999998,97.250003,96.499997,99.833333,97.166669
Client_3,86.083335,91.750002,94.333333,95.916665,95.333332,96.749997,97.166669,97.166669,97.416669,97.416669
Client_4,87.916666,92.333335,93.416667,95.166665,95.666665,95.833331,95.833331,97.916669,98.083335,98.083335
Client_5,86.333334,92.083335,93.250000,94.583333,95.416665,96.166664,96.499997,95.916665,96.499997,96.499997

======================================================================

## Visualization

In [13]:
# Plot 1: Median accuracy across all clients
print("Creating median accuracy plot...")

plt.figure(figsize=(12, 7))
rounds = range(1, NUM_ROUNDS + 1)

median_accs = []
std_accs = []
for r in range(NUM_ROUNDS):
    round_accs = [client_test_acc_history[i][r] * 100 for i in range(NUM_CLIENTS)]
    median_accs.append(np.median(round_accs))
    std_accs.append(np.std(round_accs))

plt.plot(rounds, median_accs, marker='o', linewidth=3, markersize=8, 
         color='#2E86AB', label='Median Test Accuracy')
plt.fill_between(rounds, 
                 np.array(median_accs) - np.array(std_accs),
                 np.array(median_accs) + np.array(std_accs),
                 alpha=0.3, color='#A8DADC', label='±1 Std Dev')

plt.title('Median Test Accuracy - Adaptive Epochs + Weight Rejection', 
          fontsize=16, fontweight='bold')
plt.xlabel('Communication Round', fontsize=13)
plt.ylabel('Test Accuracy (%)', fontsize=13)
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.ylim([50, 100])

plt.savefig(f'{RESULTS_DIR}/plots/median_accuracy.png', dpi=300, bbox_inches='tight')
print(f"✓ Saved: median_accuracy.png")
plt.close()

Creating median accuracy plot...
✓ Saved: median_accuracy.png

In [14]:
# Plot 2: Individual client accuracy curves (dynamic grid)
print("Creating individual client accuracy plots (dynamic grid)...")

import math
grid_cols = int(math.ceil(math.sqrt(NUM_CLIENTS)))
grid_rows = int(math.ceil(NUM_CLIENTS / grid_cols))

fig, axes = plt.subplots(grid_rows, grid_cols, figsize=(grid_cols * 3, grid_rows * 3))
fig.suptitle('Test Accuracy per Client - Adaptive Epochs + Weight Rejection', 
             fontsize=20, fontweight='bold', y=0.995)

# Normalize axes to a 2D array for consistent indexing
axes = np.array(axes).reshape(grid_rows, grid_cols)

rounds = range(1, NUM_ROUNDS + 1)

for client_id in range(NUM_CLIENTS):
    row = client_id // grid_cols
    col = client_id % grid_cols
    ax = axes[row, col]
    
    accs = [acc * 100 for acc in client_test_acc_history[client_id]]
    final_acc = accs[-1]
    improvement = final_acc - accs[0]
    rejections = total_rejections_per_client[client_id]
    adaptive = total_adaptive_rounds[client_id]
    
    color = '#2E86AB' if improvement >= 0 else '#E63946'
    ax.plot(rounds, accs, marker='o', linewidth=2, markersize=4, color=color)
    ax.fill_between(rounds, accs, alpha=0.3, color=color)
    
    title_color = 'green' if improvement >= 0 else 'red'
    ax.set_title(f'C{client_id+1} ({improvement:+.1f}%) R:{rejections} A:{adaptive}', 
                fontsize=9, fontweight='bold', color=title_color)
    
    ax.text(NUM_ROUNDS, final_acc, f'{final_acc:.0f}%', 
            fontsize=8, fontweight='bold', verticalalignment='center',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.7))
    
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.set_ylim(0, 100)
    ax.set_xlim(0.5, NUM_ROUNDS + 0.5)
    
    if row == grid_rows - 1:
        ax.set_xlabel('Round', fontsize=8)
    if col == 0:
        ax.set_ylabel('Accuracy (%)', fontsize=8)

# Hide any unused subplot axes
for idx in range(NUM_CLIENTS, grid_rows * grid_cols):
    row = idx // grid_cols
    col = idx % grid_cols
    axes[row, col].axis('off')

plt.tight_layout()
plt.savefig(f'{RESULTS_DIR}/plots/all_clients_grid.png', dpi=300, bbox_inches='tight')
print(f"✓ Saved: all_clients_grid.png")
plt.close()

Creating individual client accuracy plots (dynamic grid)...
✓ Saved: all_clients_grid.png

In [15]:
# Plot 3: Rejection heatmap
print("Creating weight rejection heatmap...")

plt.figure(figsize=(14, 10))

rejection_matrix = np.zeros((NUM_CLIENTS, NUM_ROUNDS))
for i in range(NUM_CLIENTS):
    for j in range(NUM_ROUNDS):
        rejection_matrix[i, j] = client_rejections[i][j]

plt.imshow(rejection_matrix, cmap='RdYlGn_r', aspect='auto', interpolation='nearest')
plt.colorbar(label='Rejected (1=Yes, 0=No)')
plt.title('Weight Rejection Status per Client per Round', fontsize=16, fontweight='bold')
plt.xlabel('Communication Round', fontsize=13)
plt.ylabel('Client ID', fontsize=13)
plt.tight_layout()

plt.savefig(f'{RESULTS_DIR}/plots/rejection_heatmap.png', dpi=300, bbox_inches='tight')
print(f"✓ Saved: rejection_heatmap.png")
plt.close()

Creating weight rejection heatmap...
✓ Saved: rejection_heatmap.png

In [16]:
# Plot 4: Epochs distribution
print("Creating epochs distribution plot...")

plt.figure(figsize=(12, 7))

epochs_matrix = []
for r in range(NUM_ROUNDS):
    round_epochs = [client_epochs_used[i][r] for i in range(NUM_CLIENTS)]
    epochs_matrix.append(round_epochs)

bp = plt.boxplot(epochs_matrix, positions=range(1, NUM_ROUNDS + 1), 
                 widths=0.6, patch_artist=True,
                 boxprops=dict(facecolor='lightblue', color='blue'),
                 medianprops=dict(color='red', linewidth=2))

plt.title('Epochs Distribution per Round (Fixed + Adaptive)', 
          fontsize=16, fontweight='bold')
plt.xlabel('Communication Round', fontsize=13)
plt.ylabel('Epochs Used', fontsize=13)
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()

plt.savefig(f'{RESULTS_DIR}/plots/epochs_distribution.png', dpi=300, bbox_inches='tight')
print(f"✓ Saved: epochs_distribution.png")
plt.close()

print("\n✅ All plots generated!\n")

Creating epochs distribution plot...
✓ Saved: epochs_distribution.png

✅ All plots generated!

## Save Results

In [17]:
# Save results and model
print("Saving results...")

results_data = {
    'client_test_acc_history': client_test_acc_history,
    'client_train_acc_history': client_train_acc_history,
    'client_rejections': client_rejections,
    'client_epochs_used': client_epochs_used,
    'client_adaptive_rounds': client_adaptive_rounds,
    'final_test_accs': final_test_accs,
    'final_train_accs': final_train_accs,
    'config': {
        'num_clients': NUM_CLIENTS,
        'num_rounds': NUM_ROUNDS,
        'fixed_epochs': FIXED_EPOCHS,
        'max_adaptive_epochs': MAX_ADAPTIVE_EPOCHS,
        'num_bottom_clients': NUM_BOTTOM_CLIENTS,
        'batch_size': BATCH_SIZE
    }
}

np.save(f'{RESULTS_DIR}/training_results.npy', results_data, allow_pickle=True)
print(f"✓ Results saved: {RESULTS_DIR}/training_results.npy")

# Save global model
global_model.save(f'{RESULTS_DIR}/global_model.h5')
print(f"✓ Model saved: {RESULTS_DIR}/global_model.h5")

print("\n✅ COMPLETE! All results saved to:", RESULTS_DIR)

Saving results...
✓ Results saved: results_adaptive_weight_rejection_60_per_class_50_clients/training_results.npy
✓ Model saved: results_adaptive_weight_rejection_60_per_class_50_clients/global_model.h5

✅ COMPLETE! All results saved to: results_adaptive_weight_rejection_60_per_class_50_clients